// ============ LESSON DATA ============
const LESSONS = [

// ==================== ALPHABET ====================

{id:'a1',type:'alpha',num:'A1',title:'Alef · Be · Pe · Te · Se',fa:'ا ب پ ت ث',
intro:'Welcome to Persian! We start with the first five letters. Persian reads right to left, and most letters connect like cursive. Notice Be, Pe, Te, Se all share the same body — only their dots differ!',
chars:[
  {l:'ا',n:'Alef',r:'ā / a',d:'Like "a" in father. Alef is a vowel carrier and does NOT connect to the next letter.',nc:true},
  {l:'ب',n:'Be',r:'b',d:'Like "b" in book. One dot below the baseline.'},
  {l:'پ',n:'Pe',r:'p',d:'Like "p" in pen. Three dots below — Persian-only, not in Arabic!'},
  {l:'ت',n:'Te',r:'t',d:'Like "t" in ten. Two dots above.'},
  {l:'ث',n:'Se',r:'s',d:'Like "s" in sun. Three dots above. Rare in everyday Persian.'},
],
forms:[
  {c:'ا',n:'Alef',s:'ا',i:'اَ',m:'ـا',f:'ـا',nc:true},
  {c:'ب',n:'Be',s:'ب',i:'بـ',m:'ـبـ',f:'ـب'},
  {c:'پ',n:'Pe',s:'پ',i:'پـ',m:'ـپـ',f:'ـپ'},
  {c:'ت',n:'Te',s:'ت',i:'تـ',m:'ـتـ',f:'ـت'},
  {c:'ث',n:'Se',s:'ث',i:'ثـ',m:'ـثـ',f:'ـث'},
],
vocab:[
  {fa:'آب',ro:'āb',en:'water'},{fa:'بابا',ro:'bābā',en:'dad'},
  {fa:'تاب',ro:'tāb',en:'swing / light'},{fa:'پِدَر',ro:'pedar',en:'father (formal)'},
  {fa:'باب',ro:'bāb',en:'door / chapter'},
],
sentences:[
  {fa:'بابا آب داد.',ro:'Bābā āb dād.',en:'Dad gave water. (Classic Persian primer!)'},
  {fa:'آب تاب دارد.',ro:'Āb tāb dārad.',en:'The water shines.'},
],
culture:{icon:'📜',tag:'Primer',title:'The Sentence Every Iranian Child Reads First',
fa:'بابا آب داد.',ro:'Bābā āb dād.',en:'"Dad gave water."',
body:'For over a century this three-word sentence has opened every Persian literacy primer. Water (آب) holds sacred status in Persian culture — associated with generosity, life, and purity. Rivers, fountains, and reflecting pools run through Persian gardens, poetry, and architecture alike.'},
quiz:[
  {q:'Name this letter:',c:'ب',opts:['Alef','Be','Pe','Te'],a:1},
  {q:'Which letter does NOT connect leftward?',c:'',opts:['ب Be','پ Pe','ا Alef','ت Te'],a:2},
  {q:'آب means:',c:'آب',opts:['Fire','Water','Earth','Wind'],a:1},
  {q:'Pe (پ) has how many dots?',c:'پ',opts:['One below','Two above','Three below','None'],a:2},
  {q:'پِدَر means:',c:'پِدَر',opts:['Mother','Brother','Father','Child'],a:2},
]},

{id:'a2',type:'alpha',num:'A2',title:'Jim · Che · He · Khe · Dal',fa:'ج چ ح خ د',
intro:'ج چ ح خ all share the same body — only dots differ! Dal is our second non-connector.',
chars:[
  {l:'ج',n:'Jim',r:'j',d:'Like "j" in jar. One dot below the curve.'},
  {l:'چ',n:'Che',r:'ch',d:'Like "ch" in chair. Three dots below. Persian-only!'},
  {l:'ح',n:'He (Jimi)',r:'h',d:'Breathy "h". Same body as Jim/Che but NO dots.'},
  {l:'خ',n:'Khe',r:'kh',d:'Guttural like Scottish "loch". One dot above.'},
  {l:'د',n:'Dal',r:'d',d:'Like "d" in door. Does NOT connect left.',nc:true},
],
forms:[
  {c:'ج',n:'Jim',s:'ج',i:'جـ',m:'ـجـ',f:'ـج'},
  {c:'چ',n:'Che',s:'چ',i:'چـ',m:'ـچـ',f:'ـچ'},
  {c:'ح',n:'He',s:'ح',i:'حـ',m:'ـحـ',f:'ـح'},
  {c:'خ',n:'Khe',s:'خ',i:'خـ',m:'ـخـ',f:'ـخ'},
  {c:'د',n:'Dal',s:'د',i:'دـ',m:'ـد',f:'ـد',nc:true},
],
vocab:[
  {fa:'جان',ro:'jān',en:'soul / dear'},{fa:'چای',ro:'chāy',en:'tea'},
  {fa:'دَر',ro:'dar',en:'door / in'},{fa:'خانه',ro:'khāne',en:'house / home'},
  {fa:'باد',ro:'bād',en:'wind'},
],
sentences:[
  {fa:'چای داری؟',ro:'Chāy dāri?',en:'Do you have any tea?'},
  {fa:'خانه‌ام جادار است.',ro:'Khāne-am jādār ast.',en:'My house is spacious.'},
],
culture:{icon:'🍵',tag:'Culture',title:'چای — Tea & Persian Hospitality',
fa:'چای نخوردی؟',ro:'Chāy nakhordī?',en:'"Haven\'t you had tea yet?"',
body:'Offering tea (چای) is the first act of Persian hospitality. A host who hasn\'t offered tea has not truly welcomed you. Persian tea is brewed strong in a small glass (استکان estekān), taken with rock sugar (نبات nabāt) held between the teeth while sipping. Refusing tea feels like refusing friendship.'},
quiz:[
  {q:'چ sounds like:',c:'چ',opts:['"j" in jar','"ch" in chair','"kh" in loch','"h" breathy'],a:1},
  {q:'Which does NOT connect leftward?',c:'',opts:['ج Jim','چ Che','ح He','د Dal'],a:3},
  {q:'خانه means:',c:'خانه',opts:['Tea','Door','Home','Soul'],a:2},
  {q:'چای means:',c:'چای',opts:['Coffee','Water','Tea','Milk'],a:2},
  {q:'Khe (خ) sounds like:',c:'خ',opts:['"k" in key','"ch" in chair','Scottish "ch" in loch','"h" in hat'],a:2},
]},

{id:'a3',type:'alpha',num:'A3',title:'Zal · Re · Ze · Zhe · Sin',fa:'ذ ر ز ژ س',
intro:'Four non-connectors in one lesson! The Re-family sit below the baseline and sweep right. Sin has three "teeth" on top and connects normally.',
chars:[
  {l:'ذ',n:'Zal',r:'z',d:'Like "z" in zone. Does NOT connect left.',nc:true},
  {l:'ر',n:'Re',r:'r',d:'A flapped/rolled "r". Does NOT connect left.',nc:true},
  {l:'ز',n:'Ze',r:'z',d:'Like "z" in zone. Does NOT connect left.',nc:true},
  {l:'ژ',n:'Zhe',r:'zh',d:'Like "s" in measure or French "j". Does NOT connect left.',nc:true},
  {l:'س',n:'Sin',r:'s',d:'Like "s" in sea. Three teeth on top. Connects normally.'},
],
forms:[
  {c:'ذ',n:'Zal',s:'ذ',i:'ذ',m:'ـذ',f:'ـذ',nc:true},
  {c:'ر',n:'Re',s:'ر',i:'ر',m:'ـر',f:'ـر',nc:true},
  {c:'ز',n:'Ze',s:'ز',i:'ز',m:'ـز',f:'ـز',nc:true},
  {c:'ژ',n:'Zhe',s:'ژ',i:'ژ',m:'ـژ',f:'ـژ',nc:true},
  {c:'س',n:'Sin',s:'س',i:'سـ',m:'ـسـ',f:'ـس'},
],
vocab:[
  {fa:'سَر',ro:'sar',en:'head'},{fa:'زَر',ro:'zar',en:'gold'},
  {fa:'سَرد',ro:'sard',en:'cold'},{fa:'رَز',ro:'raz',en:'grapevine / secret'},
  {fa:'دَرس',ro:'dars',en:'lesson'},
],
sentences:[
  {fa:'هوا سرد است.',ro:'Havā sard ast.',en:'The weather is cold.'},
  {fa:'دَرس یاد می‌گیرم.',ro:'Dars yād migiram.',en:'I am learning a lesson.'},
],
culture:{icon:'🌹',tag:'Poetry',title:'Rumi — Master of Persian Verse',
fa:'بشنو این نی چون شکایت می‌کند.',ro:'Beshno in ney chon shekāyat mikonad.',en:'"Listen to the reed, how it tells a tale of separation."',
body:'These are the opening words of the Masnavi by Rūmī (1207–1273), one of history\'s most widely read poets. The ney (نی) is a reed flute — a metaphor for the soul separated from its source. Notice how the rolling Re (ر) flows through this verse like water. Rumi wrote in Persian while living in what is now Turkey.'},
quiz:[
  {q:'How many non-connectors are in this lesson?',c:'',opts:['2','3','4','5'],a:2},
  {q:'ژ (Zhe) sounds like:',c:'ژ',opts:['"z" in zone','"s" in measure','"ch" in chair','"r" in run'],a:1},
  {q:'سَرد means:',c:'سَرد',opts:['Hot','Cold','Rain','Wind'],a:1},
  {q:'Sin (س) has how many teeth?',c:'س',opts:['One','Two','Three','Four'],a:2},
  {q:'زَر means:',c:'زَر',opts:['Silver','Gold','Copper','Iron'],a:1},
]},

{id:'a4',type:'alpha',num:'A4',title:'Shin · Sad · Zad · Ta · Za',fa:'ش ص ض ط ظ',
intro:'Shin is Sin with three dots above. Sad, Zad, Ta, Za are "emphatic" letters — heavier sounds from deeper in the mouth. In spoken Persian the distinction is subtle but important for correct spelling.',
chars:[
  {l:'ش',n:'Shin',r:'sh',d:'Like "sh" in shoe. Three dots above Sin\'s body.'},
  {l:'ص',n:'Sad',r:'s (emphatic)',d:'Heavier "s" — a loop with a small tooth.'},
  {l:'ض',n:'Zad',r:'z (emphatic)',d:'Heavier "z". One dot above Sad\'s shape.'},
  {l:'ط',n:'Ta (Tarsim)',r:'t (emphatic)',d:'Heavier "t". A tall vertical stroke on a loop.'},
  {l:'ظ',n:'Za (Moajame)',r:'z (emphatic)',d:'Heavier "z". One dot above Ta.'},
],
forms:[
  {c:'ش',n:'Shin',s:'ش',i:'شـ',m:'ـشـ',f:'ـش'},
  {c:'ص',n:'Sad',s:'ص',i:'صـ',m:'ـصـ',f:'ـص'},
  {c:'ض',n:'Zad',s:'ض',i:'ضـ',m:'ـضـ',f:'ـض'},
  {c:'ط',n:'Ta',s:'ط',i:'طـ',m:'ـطـ',f:'ـط'},
  {c:'ظ',n:'Za',s:'ظ',i:'ظـ',m:'ـظـ',f:'ـظ'},
],
vocab:[
  {fa:'شَب',ro:'shab',en:'night'},{fa:'شادی',ro:'shādi',en:'happiness'},
  {fa:'صَبا',ro:'sabā',en:'morning breeze'},{fa:'طَبیب',ro:'tabib',en:'doctor'},
  {fa:'شب بخیر',ro:'shab bekheyr',en:'good night'},
],
sentences:[
  {fa:'شب بخیر.',ro:'Shab bekheyr.',en:'Good night.'},
  {fa:'شادی بخش باد.',ro:'Shādi bakhsh bād.',en:'May it bring joy.'},
],
culture:{icon:'🎨',tag:'Art',title:'Persian Miniature Painting',
fa:'نگارگری ایرانی',ro:'Negārgari-ye Irāni',en:'"Persian Painting"',
body:'Persian miniature painting (نگارگری) developed from the 13th century. These jewel-like works illustrate epic poetry — especially Ferdowsi\'s Shahnameh. Artists used lapis lazuli blues, gold leaf, and extraordinary detail. Safavid court painters of Isfahan (16th–17th c.) were the masters. Night scenes — شَب (shab) — gardens under moonlight — are a beloved recurring theme.'},
quiz:[
  {q:'Shin (ش) differs from Sin (س) by:',c:'ش',opts:['One dot below','Two dots','Three dots above','A loop'],a:2},
  {q:'شَب means:',c:'شَب',opts:['Morning','Noon','Evening','Night'],a:3},
  {q:'شب بخیر means:',c:'شب بخیر',opts:['Good morning','Good night','Hello','Goodbye'],a:1},
  {q:'Which letter has a dot above the Ta (ط) shape?',c:'',opts:['ش Shin','ص Sad','ط Ta','ظ Za'],a:3},
  {q:'شادی means:',c:'شادی',opts:['Sadness','Anger','Happiness','Fear'],a:2},
]},

{id:'a5',type:'alpha',num:'A5',title:'Ain · Ghain · Fe · Qaf · Kaf',fa:'ع غ ف ق ک',
intro:'Ain is unique — a voiced pharyngeal with no English equivalent. Ghain is Ain with a dot. Fe, Qaf, Kaf are more approachable for English speakers.',
chars:[
  {l:'ع',n:'Ain',r:"'",d:"A unique guttural from deep in the throat. No English equivalent — a pharyngeal constriction."},
  {l:'غ',n:'Ghain',r:'gh',d:'A gargling sound, like a French "r". One dot above Ain.'},
  {l:'ف',n:'Fe',r:'f',d:'Like "f" in fun. One dot above a curved body.'},
  {l:'ق',n:'Qaf',r:'q',d:'A deep "k" from the back of the throat. Two dots above.'},
  {l:'ک',n:'Kaf',r:'k',d:'Like "k" in key. Distinctive diagonal stroke inside.'},
],
forms:[
  {c:'ع',n:'Ain',s:'ع',i:'عـ',m:'ـعـ',f:'ـع'},
  {c:'غ',n:'Ghain',s:'غ',i:'غـ',m:'ـغـ',f:'ـغ'},
  {c:'ف',n:'Fe',s:'ف',i:'فـ',m:'ـفـ',f:'ـف'},
  {c:'ق',n:'Qaf',s:'ق',i:'قـ',m:'ـقـ',f:'ـق'},
  {c:'ک',n:'Kaf',s:'ک',i:'کـ',m:'ـکـ',f:'ـک'},
],
vocab:[
  {fa:'عَشق',ro:"'eshq",en:'love / passion'},{fa:'کِتاب',ro:'ketāb',en:'book'},
  {fa:'غَم',ro:'gham',en:'sorrow'},{fa:'فارسی',ro:'Fārsi',en:'Persian language'},
  {fa:'عکس',ro:"'aks",en:'photo / image'},
],
sentences:[
  {fa:'کِتاب دارم.',ro:'Ketāb dāram.',en:'I have a book.'},
  {fa:'عشق زندگی است.',ro:"'Eshq zendegi ast.",en:'Love is life.'},
],
culture:{icon:'💫',tag:'Proverb',title:'Drop by Drop — A Persian Proverb',
fa:'قطره قطره دریا می‌شود.',ro:'Qatre qatre daryā mishavad.',en:'"Drop by drop, it becomes a sea."',
body:'This beloved proverb encourages perseverance. Every vocabulary word memorised, every letter practised — slowly becomes an ocean of knowledge. قطره (qatre) = drop · دریا (daryā) = sea. The Caspian Sea bordering northern Iran is called دریای خزر (Daryā-ye Khazar).'},
quiz:[
  {q:'عَشق means:',c:'عَشق',opts:['Sorrow','Joy','Love','Anger'],a:2},
  {q:'Ghain (غ) is Ain (ع) plus:',c:'غ',opts:['No dots','One dot above','Two dots','Three dots'],a:1},
  {q:'کِتاب means:',c:'کِتاب',opts:['Pen','Paper','Notebook','Book'],a:3},
  {q:'Fe (ف) sounds like:',c:'ف',opts:['"v" in van','"f" in fun','"p" in pen','"b" in bat'],a:1},
  {q:'فارسی means:',c:'فارسی',opts:['Iran','Arabic','Persian language','A city'],a:2},
]},

{id:'a6',type:'alpha',num:'A6',title:'Gaf · Lam · Mim · Nun · Vav',fa:'گ ل م ن و',
intro:'Gaf is a purely Persian letter — not in Arabic. Lam, Mim, Nun are very common. Vav is both consonant "v" and long vowels "o"/"u".',
chars:[
  {l:'گ',n:'Gaf',r:'g',d:'Like "g" in go. Persian-only — not in Arabic! Two diagonal strokes added to Kaf.'},
  {l:'ل',n:'Lam',r:'l',d:'Like "l" in love. A tall upward stroke that curves to connect.'},
  {l:'م',n:'Mim',r:'m',d:'Like "m" in moon. A small circle with a connecting tail.'},
  {l:'ن',n:'Nun',r:'n',d:'Like "n" in now. A bowl shape with one dot above.'},
  {l:'و',n:'Vav',r:'v / o / u',d:'Like "v" in vine OR long "o"/"u". Does NOT connect left.',nc:true},
],
forms:[
  {c:'گ',n:'Gaf',s:'گ',i:'گـ',m:'ـگـ',f:'ـگ'},
  {c:'ل',n:'Lam',s:'ل',i:'لـ',m:'ـلـ',f:'ـل'},
  {c:'م',n:'Mim',s:'م',i:'مـ',m:'ـمـ',f:'ـم'},
  {c:'ن',n:'Nun',s:'ن',i:'نـ',m:'ـنـ',f:'ـن'},
  {c:'و',n:'Vav',s:'و',i:'و',m:'ـو',f:'ـو',nc:true},
],
vocab:[
  {fa:'مادر',ro:'mādar',en:'mother'},{fa:'نان',ro:'nān',en:'bread'},
  {fa:'گل',ro:'gol',en:'flower / rose'},{fa:'نام',ro:'nām',en:'name'},
  {fa:'من',ro:'man',en:'I / me'},
],
sentences:[
  {fa:'نام من لیلاست.',ro:'Nām-e man Laylāst.',en:'My name is Layla.'},
  {fa:'گل زیباست.',ro:'Gol zibāst.',en:'The flower is beautiful.'},
],
culture:{icon:'🌺',tag:'Symbol',title:'گل — The Rose in Persian Culture',
fa:'گل بی‌خار نمی‌شود.',ro:'Gol bi-khār nemishavad.',en:'"A rose does not grow without thorns."',
body:'The rose (گل) and the nightingale (بلبل bulbul) are the two great symbols of Persian poetry. The rose = beauty, the divine beloved. The nightingale weeps for the rose — the lover longing for the unattainable. This pairing appears in Hafez, Rumi, and hundreds of classical poets. When giving flowers in Iran, always use odd numbers — even numbers are for funerals.'},
quiz:[
  {q:'Gaf (گ) differs from Kaf (ک) by:',c:'گ',opts:['One dot below','Two diagonal strokes added','Three dots above','A loop'],a:1},
  {q:'Vav (و) is a non-connector?',c:'و',opts:['True','False'],a:0},
  {q:'مادر means:',c:'مادر',opts:['Father','Sister','Mother','Brother'],a:2},
  {q:'نان means:',c:'نان',opts:['Water','Tea','Bread','Rice'],a:2},
  {q:'من means:',c:'من',opts:['You','He/She','I / me','We'],a:2},
]},

{id:'a7',type:'alpha',num:'A7',title:'He · Ye — Final Letters!',fa:'ه ی',
intro:'The last two letters of the Persian alphabet! He changes shape more than any other letter. Ye is both the "y" consonant and the long "ee" vowel. You now know all 32 Persian letters!',
chars:[
  {l:'ه',n:'He (Havvaz)',r:'h',d:'Like "h" in hat. Changes shape significantly by position. In final position after a non-connector it looks like the standalone form — but it is still a final He.'},
  {l:'ی',n:'Ye',r:'y / i',d:'Like "y" in yes, OR the long "ee" vowel. Very common — also the ezāfe connector suffix.'},
],
forms:[
  {c:'ه',n:'He',s:'ه',i:'هـ',m:'ـهـ',f:'ـه',nc:false},
  {c:'ی',n:'Ye',s:'ی',i:'یـ',m:'ـیـ',f:'ـی'},
],
vocab:[
  {fa:'هَر',ro:'har',en:'every / each'},{fa:'یاد',ro:'yād',en:'memory / learning'},
  {fa:'هوا',ro:'havā',en:'weather / air'},{fa:'ایران',ro:'Irān',en:'Iran'},
  {fa:'زیبا',ro:'zibā',en:'beautiful'},{fa:'خوب',ro:'khub',en:'good'},
],
sentences:[
  {fa:'ایران زیباست.',ro:'Irān zibāst.',en:'Iran is beautiful.'},
  {fa:'هوا خوب است.',ro:'Havā khub ast.',en:'The weather is good.'},
  {fa:'یاد بگیر!',ro:'Yād begir!',en:'Learn! (Take it to memory!)'},
],
culture:{icon:'🎉',tag:'Milestone',title:'شما الفبا را یاد گرفتید!',
fa:'مبارک باشد!',ro:'Mobārak bāshad!',en:'"Congratulations!"',
body:'You now know all 32 letters of the Persian alphabet (الفبا, alefbā). The name comes from the first two letters: الف (Alef) + ب (Be). Persian uses Arabic script but adds 4 unique letters: پ چ ژ گ. You can now sound out any Persian word! قدم به قدم — qadam be qadam — step by step.'},
quiz:[
  {q:'How many letters does the Persian alphabet have?',c:'',opts:['26','28','32','36'],a:2},
  {q:'Which 4 letters exist in Persian but NOT Arabic?',c:'',opts:['ب پ ت ث','پ چ ژ گ','ج چ ح خ','ک گ ل م'],a:1},
  {q:'هوا means:',c:'هوا',opts:['Water','Air/Weather','Earth','Fire'],a:1},
  {q:'مبارک باشد means:',c:'مبارک باشد',opts:['Good night','Thank you','Congratulations','Welcome'],a:2},
  {q:'Ye (ی) can function as:',c:'ی',opts:['Only consonant "y"','Only vowel "ee"','Both consonant "y" and long vowel "ee"','Neither'],a:2},
]},

// ==================== NUMBERS ====================

{id:'n1',type:'num',num:'N1',title:'Numbers 1–10 · اعداد ۱ تا ۱۰',fa:'۱ ۲ ۳ ۴ ۵',
intro:'Persian has its own numeral shapes (Eastern Arabic numerals: ۰۱۲۳...) widely used alongside Western numerals. Note that ۴ ۵ ۶ look quite different from 4 5 6 — pay special attention to those three!',
nums1to10:[
  {f:'یک',a:'۱',r:'yek',v:'1'},{f:'دو',a:'۲',r:'do',v:'2'},{f:'سه',a:'۳',r:'se',v:'3'},
  {f:'چهار',a:'۴',r:'chahār',v:'4'},{f:'پنج',a:'۵',r:'panj',v:'5'},
  {f:'شش',a:'۶',r:'shesh',v:'6'},{f:'هفت',a:'۷',r:'haft',v:'7'},
  {f:'هشت',a:'۸',r:'hasht',v:'8'},{f:'نه',a:'۹',r:'noh',v:'9'},
  {f:'ده',a:'۱۰',r:'dah',v:'10'},
],
vocab:[
  {fa:'یک',ro:'yek',en:'1'},{fa:'دو',ro:'do',en:'2'},{fa:'سه',ro:'se',en:'3'},
  {fa:'چهار',ro:'chahār',en:'4'},{fa:'پنج',ro:'panj',en:'5'},{fa:'شش',ro:'shesh',en:'6'},
  {fa:'هفت',ro:'haft',en:'7'},{fa:'هشت',ro:'hasht',en:'8'},{fa:'نه',ro:'noh',en:'9'},
  {fa:'ده',ro:'dah',en:'10'},
],
sentences:[
  {fa:'یک چای لطفاً.',ro:'Yek chāy lotfan.',en:'One tea please.'},
  {fa:'پنج دقیقه صبر کن.',ro:'Panj daqiqe sabr kon.',en:'Wait five minutes.'},
],
culture:{icon:'🔢',tag:'Script',title:'Persian Numerals — ارقام فارسی',
fa:'۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹',ro:'0 1 2 3 4 5 6 7 8 9',en:'Eastern Arabic (Persian) numerals',
body:'The numerals used in Persian script were developed by Persian mathematicians and transmitted to Europe through Arab scholars — giving us the "Arabic" numerals we use today (0,1,2,3...). The word "algorithm" comes from al-Khwārizmī (خوارزمی), a 9th-century Persian mathematician from Khwarazm. "Algebra" comes from his book title. Persian scholars essentially gave the world modern mathematics.'},
quiz:[
  {q:'What is ۷ in Persian words?',c:'۷',opts:['شش (shesh)','هفت (haft)','هشت (hasht)','نه (noh)'],a:1},
  {q:'پنج means:',c:'پنج',opts:['Three','Four','Five','Six'],a:2},
  {q:'What does ده mean?',c:'ده',opts:['Seven','Eight','Nine','Ten'],a:3},
  {q:'The Persian numeral ۴ equals:',c:'۴',opts:['2','3','4','5'],a:2},
  {q:'"Algorithm" comes from:',c:'',opts:['A Greek word','A Persian mathematician\'s name','A Latin term','An Arabic phrase'],a:1},
]},

{id:'n2',type:'num',num:'N2',title:'Numbers 11–100 · اعداد ۱۱ تا ۱۰۰',fa:'۱۱ ۲۰ ۵۰ ۱۰۰',
intro:'Persian numbers from 11 onwards are beautifully regular. Teens end in a modified "dah" (ten). Compound numbers simply join with "o" (and).',
nums11to100:[
  {f:'یازده',a:'۱۱',r:'yāzdah',v:'11'},{f:'دوازده',a:'۱۲',r:'davāzdah',v:'12'},
  {f:'سیزده',a:'۱۳',r:'sizdah',v:'13'},{f:'چهارده',a:'۱۴',r:'chahārdah',v:'14'},
  {f:'پانزده',a:'۱۵',r:'pānzdah',v:'15'},{f:'شانزده',a:'۱۶',r:'shānzdah',v:'16'},
  {f:'هفده',a:'۱۷',r:'hefdah',v:'17'},{f:'هجده',a:'۱۸',r:'hijdah',v:'18'},
  {f:'نوزده',a:'۱۹',r:'nuzdah',v:'19'},{f:'بیست',a:'۲۰',r:'bist',v:'20'},
  {f:'سی',a:'۳۰',r:'si',v:'30'},{f:'چهل',a:'۴۰',r:'chehel',v:'40'},
  {f:'پنجاه',a:'۵۰',r:'panjāh',v:'50'},{f:'شصت',a:'۶۰',r:'shast',v:'60'},
  {f:'هفتاد',a:'۷۰',r:'haftād',v:'70'},{f:'هشتاد',a:'۸۰',r:'hashtād',v:'80'},
  {f:'نود',a:'۹۰',r:'navad',v:'90'},{f:'صد',a:'۱۰۰',r:'sad',v:'100'},
],
numRules:[
  {title:'Teens: unit + ده (dah)',body:'All teens end in a modified form of "dah" (ten): یازده (11) = یاز+ده · دوازده (12) = دواز+ده · سیزده (13) = سیز+ده, and so on through نوزده (19).'},
  {title:'Compound numbers: join with و (o)',body:'Say the ten, then "o" (and), then the unit: بیست و یک (bist-o-yek) = 21 · سی و پنج (si-o-panj) = 35 · چهل و هفت (chehel-o-haft) = 47.'},
],
vocab:[
  {fa:'یازده',ro:'yāzdah',en:'11'},{fa:'دوازده',ro:'davāzdah',en:'12'},
  {fa:'بیست',ro:'bist',en:'20'},{fa:'سی',ro:'si',en:'30'},
  {fa:'پنجاه',ro:'panjāh',en:'50'},{fa:'صد',ro:'sad',en:'100'},
  {fa:'بیست و یک',ro:'bist-o-yek',en:'21'},{fa:'سی و پنج',ro:'si-o-panj',en:'35'},
],
sentences:[
  {fa:'بیست و سه سالمه.',ro:'Bist-o-se sālame.',en:'I am 23 years old.'},
  {fa:'این کتاب پنجاه هزار تومانه.',ro:'In ketāb panjāh hezār tomāne.',en:'This book costs 50,000 tomans.'},
],
culture:{icon:'🧮',tag:'Maths',title:'al-Khwārizmī — Father of Algebra',
fa:'الگوریتم',ro:'Algoritem',en:'"Algorithm" — from a Persian name',
body:'The word "algorithm" comes from al-Khwārizmī (خوارزمی), a 9th-century Persian mathematician. His name, Latinised as Algoritmi, gave us "algorithm". "Algebra" comes from his book title al-Kitāb al-mukhtaṣar fī ḥisāb al-jabr. Persian scholars essentially gave the world modern mathematics.'},
quiz:[
  {q:'How do you say 21 in Persian?',c:'',opts:['یک و بیست','بیست و یک','یک بیست','بیستم یک'],a:1},
  {q:'شصت means:',c:'شصت',opts:['50','60','70','80'],a:1},
  {q:'Teens in Persian end with a modified form of:',c:'',opts:['صد (hundred)','هزار (thousand)','ده (ten)','یک (one)'],a:2},
  {q:'What is 35 in Persian?',c:'',opts:['سی و پنج','پنج و سی','پنجاه و سه','سی پنج'],a:0},
  {q:'The word "algebra" comes from:',c:'',opts:['A Greek philosopher','A Persian mathematician\'s book','An Arabic number','A Latin word'],a:1},
]},

{id:'n3',type:'num',num:'N3',title:'Numbers 100–1000 & Currency',fa:'۱۰۰ ۵۰۰ ۱۰۰۰',
intro:'Hundreds and thousands in Persian are straightforward. We also cover Iran\'s currency system here — essential knowledge for shopping, since prices involve very large numbers!',
nums100s:[
  {f:'صد',a:'۱۰۰',r:'sad',v:'100'},{f:'دویست',a:'۲۰۰',r:'devist',v:'200'},
  {f:'سیصد',a:'۳۰۰',r:'sisad',v:'300'},{f:'چهارصد',a:'۴۰۰',r:'chahārsad',v:'400'},
  {f:'پانصد',a:'۵۰۰',r:'pānsad',v:'500'},{f:'ششصد',a:'۶۰۰',r:'sheshsad',v:'600'},
  {f:'هفتصد',a:'۷۰۰',r:'haftsad',v:'700'},{f:'هشتصد',a:'۸۰۰',r:'hashtsad',v:'800'},
  {f:'نهصد',a:'۹۰۰',r:'nohsad',v:'900'},{f:'هزار',a:'۱۰۰۰',r:'hezār',v:'1000'},
],
numRules:[
  {title:'200 is irregular: دویست (devist)',body:'All other hundreds are regular — unit + صد: سیصد (300) · چهارصد (400) · پانصد (500) etc. Only 200 is irregular: دویست (devist).'},
  {title:'Combine hundreds with و (o)',body:'Use "o" (and) to join: ۱۲۵ = صد و بیست و پنج · ۳۴۷ = سیصد و چهل و هفت.'},
  {title:'Thousands: هزار (hezār)',body:'1,000 = هزار · 2,000 = دو هزار · 10,000 = ده هزار · 100,000 = صد هزار · 1,000,000 = یک میلیون. Million (میلیون) is used in everyday speech for prices.'},
  {title:'Currency: Rial vs Toman',body:'Iran\'s official currency is the Rial (ریال). However, Iranians always speak in Tomans (تومان). 1 Toman = 10 Rials. A price tag showing 50,000 Rials = 5,000 Tomans. Simply divide Rials by 10 to get Tomans. Since prices in Rials are enormous, Iranians naturally use Tomans — and increasingly میلیون (million) in everyday talk.'},
],
vocab:[
  {fa:'صد',ro:'sad',en:'100'},{fa:'دویست',ro:'devist',en:'200'},
  {fa:'پانصد',ro:'pānsad',en:'500'},{fa:'هزار',ro:'hezār',en:'1,000'},
  {fa:'ده هزار',ro:'dah hezār',en:'10,000'},{fa:'یک میلیون',ro:'yek milyon',en:'1,000,000'},
  {fa:'تومان',ro:'tomān',en:'Toman (used in speech)'},{fa:'ریال',ro:'riyāl',en:'Rial (official)'},
],
sentences:[
  {fa:'این ساعت پانصد هزار تومانه.',ro:"In sā'at pānsad hezār tomāne.",en:'This watch costs 500,000 tomans.'},
  {fa:'هزار سال پیش.',ro:'Hezār sāl pish.',en:'One thousand years ago.'},
],
culture:{icon:'💰',tag:'Currency',title:'Rials & Tomans — A Number Puzzle',
fa:'قیمتش چنده؟',ro:'Qimateshe chande?',en:'"How much does it cost?"',
body:'Iran\'s official currency is the Rial (ریال). But Iranians almost never use Rials in conversation — they use Tomans (تومان). 1 Toman = 10 Rials. So "پنج هزار تومان" (5,000 tomans) appears as 50,000 Rials on a price tag. To convert: divide Rials by 10. Since 2020, Iran has been officially transitioning to call the currency Toman, removing the extra zero. A modest restaurant meal might be "دویست هزار تومان" (200,000 tomans). Don\'t panic — just count zeros!'},
quiz:[
  {q:'دویست means:',c:'دویست',opts:['100','200','300','2000'],a:1},
  {q:'How do you say 325 in Persian?',c:'',opts:['سیصد بیست پنج','سیصد و بیست و پنج','بیست و پنج صد','سی و دویست و پنج'],a:1},
  {q:'هزار means:',c:'هزار',opts:['100','500','1,000','10,000'],a:2},
  {q:'1 Toman equals:',c:'',opts:['1 Rial','5 Rials','10 Rials','100 Rials'],a:2},
  {q:'How do you say 2,000 in Persian?',c:'',opts:['هزار دو','دو هزار','دوهزار یک','بیست صد'],a:1},
]},

// ==================== GRAMMAR ====================

{id:'g1',type:'gram',num:'G1',title:'Verbs I — To Be, To Have, To Go',fa:'بودن · داشتن · رفتن',
intro:'Persian verb conjugation is wonderfully regular. Every verb has two stems: a present stem and a past stem. Almost every tense is built from just these two. We start with the three most essential verbs in the language.',
verbs:[
  {
    inf:'بودن', ro:'budan', en:'to be',
    pstem:'هست', pstemRo:'hast', pastStem:'بود', pastStemRo:'bud',
    note:'بودن is the most important Persian verb. In daily speech, short enclitic suffixes are attached directly to adjectives instead of the full هست- forms. Both patterns are shown below. Negative: نیستم (nistam) = I am not.',
    present:[
      {p:'من',pr:'man',e:'I',f:'هستم',ro:'hastam'},
      {p:'تو',pr:'to',e:'you (sg.)',f:'هستی',ro:'hasti'},
      {p:'او / اون',pr:'u / un',e:'he/she',f:'هست / است',ro:'hast / ast'},
      {p:'ما',pr:'mā',e:'we',f:'هستیم',ro:'hastim'},
      {p:'شما',pr:'shomā',e:'you (pl./formal)',f:'هستید',ro:'hastid'},
      {p:'آنها',pr:'ānhā',e:'they',f:'هستند',ro:'hastand'},
    ],
    past:[
      {p:'من',pr:'man',f:'بودم',ro:'budam'},
      {p:'تو',pr:'to',f:'بودی',ro:'budi'},
      {p:'او',pr:'u',f:'بود',ro:'bud'},
      {p:'ما',pr:'mā',f:'بودیم',ro:'budim'},
      {p:'شما',pr:'shomā',f:'بودید',ro:'budid'},
      {p:'آنها',pr:'ānhā',f:'بودند',ro:'budand'},
    ],
    spoken:[
      {p:'من',e:'I',   suf:'ـَم',sRo:'-am', ex:'خوبم',   exRo:'khubam',  exEn:'I am well'},
      {p:'تو',e:'you', suf:'ـی', sRo:'-i',  ex:'کجایی؟',exRo:'kojāyi?', exEn:'Where are you?'},
      {p:'او',e:'he/she',suf:'ـه',sRo:'-e', ex:'خوبه',   exRo:'khube',   exEn:'He/she is well'},
      {p:'ما',e:'we',  suf:'ـیم',sRo:'-im', ex:'خوبیم',  exRo:'khubim',  exEn:'We are well'},
      {p:'شما',e:'you pl.',suf:'ـید',sRo:'-id',ex:'خوبید؟',exRo:'khubid?',exEn:'Are you (all) well?'},
      {p:'آنها',e:'they',suf:'ـَند',sRo:'-and',ex:'خوبند',exRo:'khuband',exEn:'They are well'},
    ],
  },
  {
    inf:'داشتن', ro:'dāshtan', en:'to have',
    pstem:'دار', pstemRo:'dār', pastStem:'داشت', pastStemRo:'dāsht',
    note:'داشتن uses the present stem دار- (dār-) + personal suffixes directly — no می- prefix in basic possession meaning. Negative: ندارم (nadāram) = I don\'t have.',
    present:[
      {p:'من',pr:'man',e:'I',f:'دارم',ro:'dāram'},
      {p:'تو',pr:'to',e:'you (sg.)',f:'داری',ro:'dāri'},
      {p:'او',pr:'u',e:'he/she',f:'دارد',ro:'dārad'},
      {p:'ما',pr:'mā',e:'we',f:'داریم',ro:'dārim'},
      {p:'شما',pr:'shomā',e:'you (pl.)',f:'دارید',ro:'dārid'},
      {p:'آنها',pr:'ānhā',e:'they',f:'دارند',ro:'dārand'},
    ],
    past:[
      {p:'من',pr:'man',f:'داشتم',ro:'dāshtam'},
      {p:'تو',pr:'to',f:'داشتی',ro:'dāshti'},
      {p:'او',pr:'u',f:'داشت',ro:'dāsht'},
      {p:'ما',pr:'mā',f:'داشتیم',ro:'dāshtim'},
      {p:'شما',pr:'shomā',f:'داشتید',ro:'dāshtid'},
      {p:'آنها',pr:'ānhā',f:'داشتند',ro:'dāshtand'},
    ],
  },
  {
    inf:'رفتن', ro:'raftan', en:'to go',
    pstem:'رو', pstemRo:'ro', pastStem:'رفت', pastStemRo:'raft',
    note:'رفتن follows the standard Persian verb pattern perfectly. Present tense = می- + present stem + suffix. Past = past stem + suffix. This exact pattern applies to ~95% of Persian verbs — master it once, use it forever! Negative present: نمی‌روم (nemiravam) = I don\'t go.',
    present:[
      {p:'من',pr:'man',e:'I',f:'می‌روم',ro:'miravam'},
      {p:'تو',pr:'to',e:'you (sg.)',f:'می‌روی',ro:'miravi'},
      {p:'او',pr:'u',e:'he/she',f:'می‌رود',ro:'miravad'},
      {p:'ما',pr:'mā',e:'we',f:'می‌رویم',ro:'miravim'},
      {p:'شما',pr:'shomā',e:'you (pl.)',f:'می‌روید',ro:'miravid'},
      {p:'آنها',pr:'ānhā',e:'they',f:'می‌روند',ro:'miravand'},
    ],
    past:[
      {p:'من',pr:'man',f:'رفتم',ro:'raftam'},
      {p:'تو',pr:'to',f:'رفتی',ro:'rafti'},
      {p:'او',pr:'u',f:'رفت',ro:'raft'},
      {p:'ما',pr:'mā',f:'رفتیم',ro:'raftim'},
      {p:'شما',pr:'shomā',f:'رفتید',ro:'raftid'},
      {p:'آنها',pr:'ānhā',f:'رفتند',ro:'raftand'},
    ],
  },
],
vocab:[
  {fa:'بودن',ro:'budan',en:'to be'},{fa:'داشتن',ro:'dāshtan',en:'to have'},
  {fa:'رفتن',ro:'raftan',en:'to go'},{fa:'می‌روم',ro:'miravam',en:'I go / I am going'},
  {fa:'دارم',ro:'dāram',en:'I have'},{fa:'هستم',ro:'hastam',en:'I am'},
  {fa:'نیستم',ro:'nistam',en:'I am not'},{fa:'ندارم',ro:'nadāram',en:'I don\'t have'},
],
sentences:[
  {fa:'کجا می‌روی؟',ro:'Kojā miravi?',en:'Where are you going?'},
  {fa:'به مدرسه می‌روم.',ro:'Be madrase miravam.',en:'I am going to school.'},
  {fa:'کتاب دارم.',ro:'Ketāb dāram.',en:'I have a book.'},
  {fa:'خوب هستم.',ro:'Khub hastam.',en:'I am well.'},
],
culture:{icon:'📐',tag:'Grammar',title:'The Beauty of Persian Verb Structure',
fa:'می + ریشه + پسوند = فعل',ro:'mi + rishe + pasvand = fe\'l',en:'"prefix + stem + suffix = verb"',
body:'Persian verbs are built from just two stems: the present stem and the past stem. The present tense prefix می- (mi-) is one of Persian\'s most important building blocks. Remove it → imperative command. Replace با نمی- (nemi-) → negative. The past tense adds personal suffixes directly to the past stem. Once you internalise this system — which رفتن perfectly demonstrates — conjugating any new verb becomes automatic. Persian grammar rewards learners who invest in its system.'},
quiz:[
  {q:'دارم means:',c:'دارم',opts:['I go','I am','I have','I want'],a:2},
  {q:'The present tense prefix in Persian is:',c:'می‌روم',opts:['می- (mi-)','نه- (na-)','هست- (hast-)','بود- (bud-)'],a:0},
  {q:'می‌روی means:',c:'می‌روی',opts:['I go','You go','He goes','We go'],a:1},
  {q:'The past tense of رفتن for "I" is:',c:'',opts:['رفتید','رفتیم','رفتم','رفتند'],a:2},
  {q:'نیستم means:',c:'نیستم',opts:['I am','I have','I am not','I do not have'],a:2},
]},

// ==================== CONVERSATIONAL ====================

{id:'c1',type:'conv',num:'C1',title:'Greetings & Introductions',fa:'سلام و آشنایی',
intro:'A1 level. Learn to say hello, introduce yourself, ask names, and use basic courtesy phrases. Iranians greet warmly — expect handshakes among acquaintances, sometimes a light cheek kiss among close friends.',
phrases:[
  {fa:'سلام',ro:'Salām',en:'Hello'},
  {fa:'خوبی؟',ro:'Khubi?',en:'Are you well? (informal)'},
  {fa:'خوبم، ممنون.',ro:'Khubam, mamnun.',en:"I'm well, thank you."},
  {fa:'اسمت چیه؟',ro:'Esmet chiye?',en:"What's your name? (informal)"},
  {fa:'اسمم ... است.',ro:'Esme-man ... ast.',en:'My name is ...'},
  {fa:'از آشنایی‌تون خوشحالم.',ro:'Az āshnāyi-tun khushhālam.',en:'Pleased to meet you.'},
  {fa:'خداحافظ.',ro:'Khodāhāfez.',en:'Goodbye (formal)'},
  {fa:'بعداً می‌بینمت.',ro:"Ba'dan mibinamat.",en:'See you later.'},
  {fa:'صبح بخیر.',ro:'Sobh bekheyr.',en:'Good morning.'},
  {fa:'شب بخیر.',ro:'Shab bekheyr.',en:'Good night.'},
  {fa:'حال شما چطور است؟',ro:'Hāl-e shomā chetour ast?',en:'How are you? (formal)'},
  {fa:'ممنون، شما چطورید؟',ro:'Mamnun, shomā chetourid?',en:'Thank you, and you? (formal)'},
],
dialogue:{title:'First meeting at a café in Tehran',lines:[
  {who:'A',name:'سارا Sara',fa:'سلام! اسمم ساراست. اسم تو چیه؟',ro:'Salām! Esmam Sārāst. Esm-e to chiye?',en:"Hi! My name is Sara. What's your name?"},
  {who:'B',name:'رضا Rezā',fa:'سلام سارا! منم رضام. خوشوقتم.',ro:'Salām Sārā! Manam Rezām. Khoshvagtam.',en:"Hi Sara! I'm Reza. Nice to meet you."},
  {who:'A',name:'سارا Sara',fa:'از کجایی، رضا؟',ro:'Az kojāyi, Rezā?',en:'Where are you from, Reza?'},
  {who:'B',name:'رضا Rezā',fa:'از تهرانم. تو چی؟',ro:'Az Tehrānam. To chi?',en:"I'm from Tehran. And you?"},
  {who:'A',name:'سارا Sara',fa:'منم از تهرانم! چه جالب!',ro:'Manam az Tehrānam! Che jāleb!',en:"I'm from Tehran too! How interesting!"},
]},
vocabSections:[
  {title:'Greetings — سلام و درود',items:[
    {fa:'سلام',ro:'salām',en:'hello (universal, any time of day)'},
    {fa:'درود',ro:'dorud',en:'greetings (formal / literary)'},
    {fa:'صبح بخیر',ro:'sobh bekheyr',en:'good morning'},
    {fa:'عصر بخیر',ro:"'asr bekheyr",en:'good afternoon'},
    {fa:'شب بخیر',ro:'shab bekheyr',en:'good night'},
    {fa:'خداحافظ',ro:'khodāhāfez',en:'goodbye (formal — lit. "God be your guardian")'},
    {fa:'بای',ro:'bāy',en:'bye (informal, from English)'},
    {fa:'فعلاً',ro:'felan',en:'for now / see you (very common informal farewell)'},
  ]},
  {title:'Politeness — ادب',items:[
    {fa:'ممنون',ro:'mamnun',en:'thank you (informal)'},
    {fa:'متشکرم',ro:'motashakkeram',en:'thank you (formal)'},
    {fa:'خواهش می‌کنم',ro:'khāhesh mikonam',en:"you're welcome / please"},
    {fa:'ببخشید',ro:'bebakhshid',en:'excuse me / sorry (formal)'},
    {fa:'بفرمایید',ro:'befarmayyid',en:'please go ahead / help yourself'},
    {fa:'لطفاً',ro:'lotfan',en:'please'},
    {fa:'خوش آمدید',ro:'khosh āmadid',en:'welcome'},
  ]},
  {title:'Asking About People',items:[
    {fa:'اسمت چیه؟',ro:'esmet chiye?',en:"what's your name? (informal)"},
    {fa:'اسم شما چیست؟',ro:'esm-e shomā chist?',en:"what's your name? (formal)"},
    {fa:'از کجایی؟',ro:'az kojāyi?',en:'where are you from?'},
    {fa:'کجا زندگی می‌کنی؟',ro:'kojā zendegi mikoni?',en:'where do you live?'},
    {fa:'چند سالته؟',ro:'chand sālate?',en:'how old are you?'},
    {fa:'شغلت چیه؟',ro:'shoghlat chiye?',en:'what is your job?'},
  ]},
],
culture:{icon:'🤝',tag:'Etiquette',title:"Ta'arof — The Art of Persian Politeness",
fa:'بفرمایید!',ro:'Befarmayid!',en:'"Please, go ahead / help yourself!"',
body:"Ta'arof (تعارف) is a cornerstone of Iranian social life — a ritual politeness where people offer more than they intend and decline more than they want. If you admire something in someone's home, they may offer it: \"مال شماست\" (it's yours). You must refuse at least twice. When entering a door, both people insist the other goes first — \"بفرمایید!\" Understanding ta'arof helps you navigate Iranian hospitality gracefully."},
quiz:[
  {q:'سلام means:',c:'سلام',opts:['Goodbye','Hello','Thank you','Please'],a:1},
  {q:'خوبم ممنون means:',c:'',opts:['Nice to meet you','Good morning',"I'm well, thank you",'See you later'],a:2},
  {q:'اسمت چیه means:',c:'',opts:['How are you?','Where are you from?','What is your name?','How old are you?'],a:2},
  {q:'خداحافظ means:',c:'خداحافظ',opts:['Hello','Goodbye','Welcome','Sorry'],a:1},
  {q:"Ta'arof is:",c:'',opts:['A Persian dish','A type of music','Ritual politeness','A greeting style'],a:2},
]},

{id:'c2',type:'conv',num:'C2',title:'Telling the Time & Days of the Week',fa:'ساعت و روزهای هفته',
intro:'A1–A2 level. Learn to ask and tell the time, name the days of the week, and talk about schedules. The Persian week starts on Saturday (شنبه) — Friday (جمعه) is the day off.',
phrases:[
  {fa:'ساعت چنده؟',ro:"Sā'at chande?",en:'What time is it?'},
  {fa:'ساعت سه است.',ro:"Sā'at se ast.",en:'It is 3 o\'clock.'},
  {fa:'ساعت نه و نیم.',ro:"Sā'at noh-o-nim.",en:'Half past nine (9:30).'},
  {fa:'ساعت شش و ربع.',ro:"Sā'at shesh-o-rob'.",en:'Quarter past six (6:15).'},
  {fa:'ساعت هفت و بیست دقیقه.',ro:"Sā'at haft-o-bist daqiqe.",en:'Twenty past seven (7:20).'},
  {fa:'ساعت ده کم ده.',ro:"Sā'at dah kam dah.",en:'Ten to ten (9:50).'},
  {fa:'امروز چه روزیه؟',ro:'Emruz che ruzi-ye?',en:'What day is it today?'},
  {fa:'امروز دوشنبه است.',ro:'Emruz doshanbe ast.',en:'Today is Monday.'},
  {fa:'جمعه آزادم.',ro:"Jom'e āzādam.",en:"I'm free on Friday."},
  {fa:'دیر شد!',ro:'Dir shod!',en:"We're late!"},
],
days:[
  {fa:'شنبه',ro:'shanbe',en:'Saturday — start of the Persian week'},
  {fa:'یکشنبه',ro:'yekshanbe',en:'Sunday — "one-shanbe"'},
  {fa:'دوشنبه',ro:'doshanbe',en:'Monday — "two-shanbe"'},
  {fa:'سه‌شنبه',ro:'seshanbe',en:'Tuesday — "three-shanbe"'},
  {fa:'چهارشنبه',ro:'chahārshanbe',en:'Wednesday — "four-shanbe"'},
  {fa:'پنجشنبه',ro:'panjshanbe',en:'Thursday — "five-shanbe"'},
  {fa:'جمعه',ro:"jom'e",en:"Friday — the day off in Iran"},
],
timeWords:[
  {fa:'ساعت',ro:"sā'at",en:'hour / clock / o\'clock'},
  {fa:'دقیقه',ro:'daqiqe',en:'minute'},
  {fa:'ثانیه',ro:'sāniye',en:'second'},
  {fa:'نیم',ro:'nim',en:'half'},
  {fa:'ربع',ro:"rob'",en:'quarter'},
  {fa:'الان',ro:'alān',en:'now'},
  {fa:'دیروز',ro:'diruz',en:'yesterday'},
  {fa:'امروز',ro:'emruz',en:'today'},
  {fa:'فردا',ro:'fardā',en:'tomorrow'},
  {fa:'هفته',ro:'hafte',en:'week'},
  {fa:'دیر',ro:'dir',en:'late'},
  {fa:'زود',ro:'zud',en:'early / fast'},
],
dialogue:{title:'Friends making plans over the phone',lines:[
  {who:'A',name:'نیلوفر Nilufar',fa:'ساعت چنده؟ دیرم میشه!',ro:"Sā'at chande? Diram mishe!",en:"What time is it? I'm going to be late!"},
  {who:'B',name:'امیر Amir',fa:'ساعت هشت و نیمه. کجا میری؟',ro:"Sā'at hasht-o-nime. Kojā miri?",en:"It's half past eight. Where are you going?"},
  {who:'A',name:'نیلوفر Nilufar',fa:'کلاس فارسی دارم ساعت نه.',ro:"Kelās-e Fārsi dāram sā'at noh.",en:'I have a Persian class at nine.'},
  {who:'B',name:'امیر Amir',fa:'هنوز بیست دقیقه مونده. نگران نباش!',ro:'Hanuz bist daqiqe munde. Nagarān nabāsh!',en:"There's still twenty minutes left. Don't worry!"},
  {who:'A',name:'نیلوفر Nilufar',fa:'جمعه چیکار می‌کنی؟',ro:"Jom'e chikār mikoni?",en:'What are you doing on Friday?'},
  {who:'B',name:'امیر Amir',fa:'جمعه آزادم. بریم بیرون؟',ro:"Jom'e āzādam. Berim birun?",en:"I'm free on Friday. Shall we go out?"},
]},
vocabSections:[
  {title:'Days of the Week — روزهای هفته',items:[
    {fa:'شنبه',ro:'shanbe',en:'Saturday (start of week)'},
    {fa:'یکشنبه',ro:'yekshanbe',en:'Sunday'},
    {fa:'دوشنبه',ro:'doshanbe',en:'Monday'},
    {fa:'سه‌شنبه',ro:'seshanbe',en:'Tuesday'},
    {fa:'چهارشنبه',ro:'chahārshanbe',en:'Wednesday'},
    {fa:'پنجشنبه',ro:'panjshanbe',en:'Thursday'},
    {fa:'جمعه',ro:"jom'e",en:'Friday (day off in Iran)'},
  ]},
  {title:'Telling the Time — گفتن ساعت',items:[
    {fa:'ساعت چنده؟',ro:"sā'at chande?",en:'what time is it?'},
    {fa:'ساعت ... است',ro:"sā'at ... ast",en:'it is ... o\'clock'},
    {fa:'و نیم',ro:'o nim',en:'and a half (e.g. ساعت سه و نیم = 3:30)'},
    {fa:'و ربع',ro:"o rob'",en:'and a quarter (3:15)'},
    {fa:'کم ربع',ro:"kam rob'",en:'quarter to (2:45)'},
    {fa:'و بیست دقیقه',ro:'o bist daqiqe',en:'twenty past'},
    {fa:'ظهر',ro:'zohr',en:'noon'},
    {fa:'نیمه شب',ro:'nime-shab',en:'midnight'},
  ]},
  {title:'Time Expressions',items:[
    {fa:'امروز',ro:'emruz',en:'today'},
    {fa:'دیروز',ro:'diruz',en:'yesterday'},
    {fa:'فردا',ro:'fardā',en:'tomorrow'},
    {fa:'هفته آینده',ro:'hafte-ye āyande',en:'next week'},
    {fa:'هفته پیش',ro:'hafte-ye pish',en:'last week'},
    {fa:'الان',ro:'alān',en:'now'},
    {fa:'زود باش',ro:'zud bāsh',en:'hurry up!'},
    {fa:'وقت ندارم',ro:'vaqt nadāram',en:"I don't have time"},
    {fa:'هنوز',ro:'hanuz',en:'still / yet'},
    {fa:'دیر شد',ro:'dir shod',en:"we're late / it got late"},
  ]},
],
culture:{icon:'📅',tag:'Calendar',title:'The Persian Solar Calendar — شمسی',
fa:'نوروز مبارک!',ro:'Nowruz Mobārak!',en:'"Happy New Year!"',
body:"Iran uses the Solar Hijri calendar (تقویم شمسی). Nowruz (نوروز — 'New Day') falls on the Spring Equinox, around March 20–21. The year 2025 CE = 1404 SH. The Persian week begins on Saturday (شنبه) — Friday (جمعه) is the weekend. Day names are systematic: یکشنبه = one-shanbe (Sunday), دوشنبه = two-shanbe (Monday), سه‌شنبه = three-shanbe (Tuesday) etc. Only جمعه (Friday) has a separate name, from Arabic."},
quiz:[
  {q:'ساعت چنده means:',c:'',opts:['What day is it?','What time is it?','How old are you?','Where are you?'],a:1},
  {q:'What is the day off in Iran?',c:'',opts:['Saturday','Sunday','Thursday','Friday'],a:3},
  {q:'نیم means:',c:'نیم',opts:['Quarter','Half','Minute','Hour'],a:1},
  {q:'دوشنبه means:',c:'دوشنبه',opts:['Sunday','Monday','Tuesday','Wednesday'],a:1},
  {q:'Which day starts the Persian week?',c:'',opts:['جمعه Friday','یکشنبه Sunday','شنبه Saturday','دوشنبه Monday'],a:2},
]},

{id:'c3',type:'conv',num:'C3',title:'Food, Cafés & Restaurants',fa:'غذا و رستوران',
intro:'A2 level. Order food, express preferences, and navigate a Persian restaurant. Iranian cuisine is one of the world\'s great food traditions — aromatic, subtle, and deeply connected to hospitality.',
phrases:[
  {fa:'یه چای لطفاً.',ro:'Ye chāy lotfan.',en:'One tea please.'},
  {fa:'منوی غذا دارید؟',ro:'Meno-ye ghazā dārid?',en:'Do you have a food menu?'},
  {fa:'غذای ایرانی دوست دارم.',ro:'Ghazā-ye Irāni dust dāram.',en:'I love Iranian food.'},
  {fa:'چی پیشنهاد می‌دید؟',ro:'Chi pishnahād midid?',en:'What do you recommend?'},
  {fa:'حساب لطفاً.',ro:'Hesāb lotfan.',en:'The bill please.'},
  {fa:'خیلی خوشمزه بود!',ro:'Kheyly khoshmaze bud!',en:'It was very delicious!'},
  {fa:'گیاهخوارم.',ro:'Giyāhkhāram.',en:'I am vegetarian.'},
  {fa:'نوش جان!',ro:'Nushe jān!',en:'Bon appétit! (lit. may it nourish your soul)'},
],
dialogue:{title:'At a traditional restaurant in Isfahan',lines:[
  {who:'A',name:'گارسون Waiter',fa:'بفرمایید! چی میل دارید؟',ro:'Befarmayyid! Chi meyl dārid?',en:'Welcome! What would you like?'},
  {who:'B',name:'مهمان Guest',fa:'یه چلو کباب و یه دوغ لطفاً.',ro:'Ye chelo kabāb o ye dugh lotfan.',en:'One chelo kabab and one doogh please.'},
  {who:'A',name:'گارسون Waiter',fa:'کباب کوبیده می‌خواید یا جوجه؟',ro:'Kabāb-e kubide mikhāyid yā juje?',en:'Do you want ground meat kabab or chicken?'},
  {who:'B',name:'مهمان Guest',fa:'کوبیده، ممنون. و آیا سوپ دارید؟',ro:'Kubide, mamnun. Va āyā sup dārid?',en:'Ground meat, thank you. And do you have soup?'},
  {who:'A',name:'گارسون Waiter',fa:'بله، آش رشته داریم.',ro:'Bale, āsh-e reshte dārim.',en:'Yes, we have noodle soup.'},
  {who:'B',name:'مهمان Guest',fa:'عالیه! حتماً امتحان می‌کنم.',ro:"'Āliye! Hatman emtahān mikonam.",en:"Wonderful! I'll definitely try it."},
]},
vocabSections:[
  {title:'Dishes & Drinks',items:[
    {fa:'چلو کباب',ro:'chelo kabāb',en:'rice with grilled meat — Iran\'s national dish'},
    {fa:'خورش قرمه سبزی',ro:'khoresh ghorme sabzi',en:'herb & bean stew — most beloved stew'},
    {fa:'آش رشته',ro:'āsh-e reshte',en:'noodle soup — eaten at Nowruz'},
    {fa:'دوغ',ro:'dugh',en:'yogurt drink — salty, cold, refreshing'},
    {fa:'زعفران',ro:"za'farān",en:"saffron — world's most prized spice, from Khorasan"},
    {fa:'نان',ro:'nān',en:'bread (lavash · sangak · barbari)'},
    {fa:'برنج',ro:'berenj',en:'rice (central to Persian cuisine)'},
    {fa:'چای',ro:'chāy',en:'tea'},
  ]},
  {title:'At the Restaurant',items:[
    {fa:'منو',ro:'meno',en:'menu'},
    {fa:'سفارش',ro:'sefāresh',en:'order'},
    {fa:'حساب',ro:'hesāb',en:'bill'},
    {fa:'گارسون',ro:'gārsun',en:'waiter'},
    {fa:'خوشمزه',ro:'khoshmaze',en:'delicious'},
    {fa:'تند',ro:'tond',en:'spicy'},
    {fa:'شیرین',ro:'shirin',en:'sweet'},
    {fa:'ترش',ro:'torsh',en:'sour'},
  ]},
  {title:'Dietary & Preferences',items:[
    {fa:'گیاهخوار',ro:'giyāhkhār',en:'vegetarian'},
    {fa:'حلال',ro:'halāl',en:'halal'},
    {fa:'بدون گوشت',ro:'bedun-e gusht',en:'without meat'},
    {fa:'آلرژی دارم',ro:'ālerji dāram',en:'I have an allergy'},
    {fa:'کمی',ro:'kami',en:'a little'},
    {fa:'بیشتر',ro:'bishtar',en:'more'},
    {fa:'کافیه',ro:'kāfiye',en:"that's enough"},
  ]},
],
culture:{icon:'🍽️',tag:'Food',title:'Persian Cuisine — A Living Poetry',
fa:'نوش جان!',ro:'Nushe jān!',en:'"May it nourish your soul!" (Bon appétit)',
body:"Persian food is built on aromatic herbs, dried fruits, nuts, and saffron (زعفران za'farān) — the world's most expensive spice, grown in Khorasan. Every Iranian household has its own recipe for ghorme sabzi. Bread (نان nān) comes in lavash (thin flatbread), sangak (baked on river stones), and barbari (thick oblong loaf). Tea after meals is non-negotiable."},
quiz:[
  {q:'نوش جان means:',c:'',opts:['Welcome','Goodbye','Bon appétit','Good night'],a:2},
  {q:'چلو کباب is:',c:'',opts:['A soup','Rice with grilled meat','A dessert','A drink'],a:1},
  {q:'حساب لطفاً means:',c:'',opts:['The menu please','One more please','The bill please','Thank you'],a:2},
  {q:'What is دوغ?',c:'دوغ',opts:['Sweet tea','Yogurt drink','Fruit juice','Sparkling water'],a:1},
  {q:'خیلی خوشمزه means:',c:'',opts:['Very expensive','Very spicy','Very delicious','Very small'],a:2},
]},

{id:'c4',type:'conv',num:'C4',title:'Shopping & Currency',fa:'خرید و پول',
intro:'A2 level. Persian bazaars are legendary. Learn to ask prices, bargain politely, and understand Iran\'s currency system — Rials vs Tomans — which confuses even seasoned travellers!',
phrases:[
  {fa:'این چند تومانه؟',ro:'In chand tomāne?',en:'How much is this? (in Tomans)'},
  {fa:'گرونه! تخفیف میدید؟',ro:'Girone! Takhfif midid?',en:"It's expensive! Can you give a discount?"},
  {fa:'این رو می‌خوام.',ro:'Ino mikhām.',en:'I want this one.'},
  {fa:'یه کم ارزون‌تر نمیشه؟',ro:'Ye kam arzuntar nemishe?',en:"Can't it be a little cheaper?"},
  {fa:'باشه، می‌خرم.',ro:'Bāshe, mikharam.',en:"OK, I'll buy it."},
  {fa:'فقط نگاه می‌کنم.',ro:'Faqat negāh mikonam.',en:"I'm just looking."},
  {fa:'پول خرد دارید؟',ro:'Pul-e khord dārid?',en:'Do you have change?'},
  {fa:'رسید می‌خوام.',ro:'Resid mikhām.',en:'I want a receipt.'},
],
dialogue:{title:'In the bazaar, buying a carpet',lines:[
  {who:'A',name:'مشتری Customer',fa:'سلام. این فرش چند تومانه؟',ro:'Salām. In farsh chand tomāne?',en:'Hello. How much is this carpet?'},
  {who:'B',name:'فروشنده Seller',fa:'سلام! این دست‌بافته. سه میلیونه.',ro:'Salām! In dast-bāfte. Se milyone.',en:"Hello! This is handwoven. It's three million (Tomans)."},
  {who:'A',name:'مشتری Customer',fa:'گرونه! دو میلیون چطوره؟',ro:'Girone! Do milyon chetore?',en:"That's expensive! How about two million?"},
  {who:'B',name:'فروشنده Seller',fa:'نمیشه آقا. دو و نیم، آخرین قیمته.',ro:'Nemishe āghā. Do-o-nim, ākharin ghimate.',en:"Can't do it, sir. Two and a half — final price."},
  {who:'A',name:'مشتری Customer',fa:'باشه. قبوله. بسته‌بندی می‌کنید؟',ro:'Bāshe. Qabule. Baste-bandi mikonid?',en:'OK. Deal. Can you pack it?'},
]},
vocabSections:[
  {title:'Shopping Vocabulary',items:[
    {fa:'بازار',ro:'bāzār',en:'bazaar / market (a Persian word used worldwide)'},
    {fa:'مغازه',ro:'maghāze',en:'shop / store'},
    {fa:'فروشنده',ro:'forushanide',en:'seller / shopkeeper'},
    {fa:'مشتری',ro:'moshtari',en:'customer'},
    {fa:'قیمت',ro:'qimat',en:'price'},
    {fa:'تخفیف',ro:'takhfif',en:'discount'},
    {fa:'گرون',ro:'girun',en:'expensive'},
    {fa:'ارزون',ro:'arzun',en:'cheap'},
    {fa:'چانه زدن',ro:'chāne zadan',en:'to bargain'},
  ]},
  {title:'Currency — ریال و تومان',items:[
    {fa:'ریال',ro:'riyāl',en:'Rial — official currency (rarely used in speech)'},
    {fa:'تومان',ro:'tomān',en:'Toman — 1 toman = 10 rials (always used in speech)'},
    {fa:'هزار تومان',ro:'hezār tomān',en:'1,000 tomans (= 10,000 rials)'},
    {fa:'یه میلیون تومان',ro:'ye milyon tomān',en:'1,000,000 tomans (very common for prices)'},
    {fa:'اسکناس',ro:'eskenās',en:'banknote'},
    {fa:'سکه',ro:'sekke',en:'coin'},
    {fa:'پول خرد',ro:'pul-e khord',en:'small change / loose coins'},
    {fa:'رسید',ro:'resid',en:'receipt'},
  ]},
  {title:'Things to Buy',items:[
    {fa:'فرش',ro:'farsh',en:'carpet / rug'},
    {fa:'زعفران',ro:"za'farān",en:'saffron'},
    {fa:'صنایع دستی',ro:'sanāye dasti',en:'handicrafts'},
    {fa:'مینیاتور',ro:'minyātur',en:'miniature painting'},
    {fa:'لباس',ro:'lebās',en:'clothing'},
    {fa:'کیف',ro:'kif',en:'bag / purse'},
    {fa:'جواهرات',ro:'javāherāt',en:'jewellery'},
  ]},
],
culture:{icon:'🏺',tag:'Bazaar',title:'The Persian Bazaar — بازار',
fa:'بازار',ro:'Bāzār',en:'"Market / Bazaar" — a Persian word used worldwide',
body:'The word "bazaar" comes directly from Persian (بازار). The Grand Bazaar of Tehran covers 10km² and employs over 100,000 people. Shopping here is social ritual: tea is offered, conversation flows, bargaining is expected — never accept the first price. Currency note: 1 Toman = 10 Rials. When a price sounds enormous (like 5,000,000), remember: that\'s 5 million Rials = only 500,000 Tomans. Iranians always speak in Tomans — simply divide the Rial number by 10.'},
quiz:[
  {q:'این چند تومانه means:',c:'',opts:['What is this?','How much is this?','I want this','Too expensive'],a:1},
  {q:'1 Toman equals:',c:'',opts:['1 Rial','5 Rials','10 Rials','100 Rials'],a:2},
  {q:'فقط نگاه می‌کنم means:',c:'',opts:["I'll buy it",'How much?','Just looking','Very nice'],a:2},
  {q:'"Bazaar" is a word borrowed from:',c:'',opts:['Arabic','Turkish','Persian','French'],a:2},
  {q:'باشه means:',c:'باشه',opts:['No','Maybe','OK / alright','Never'],a:2},
]},

{id:'c5',type:'conv',num:'C5',title:'Family & Friends',fa:'خانواده و دوستان',
intro:'A2–B1 level. Talk about your family, describe relationships, and discuss friendship. Family is the cornerstone of Iranian culture — multigenerational homes are common and family loyalty runs deep.',
phrases:[
  {fa:'خانواده‌ام بزرگه.',ro:"Khānevāde-am bozorge.",en:'My family is large.'},
  {fa:'چند تا برادر خواهر داری؟',ro:'Chand tā barādar khāhar dāri?',en:'How many siblings do you have?'},
  {fa:'یه برادر و دو خواهر دارم.',ro:'Ye barādar o do khāhar dāram.',en:'I have one brother and two sisters.'},
  {fa:'ازدواج کردی؟',ro:'Ezdevāj kardi?',en:'Are you married?'},
  {fa:'نه، هنوز مجردم.',ro:'Na, hanuz mojradam.',en:"No, I'm still single."},
  {fa:'دوست صمیمی‌ام رضاست.',ro:'Dust-e samimi-am Rezāst.',en:'My close friend is Reza.'},
  {fa:'با هم بزرگ شدیم.',ro:'Bā ham bozorg shodim.',en:'We grew up together.'},
],
dialogue:{title:'Catching up with an old friend',lines:[
  {who:'A',name:'شیرین Shirin',fa:'شیرین! چقدر وقته ندیدمت!',ro:'Shirin! Cheghadr vaghte nadidamat!',en:"Shirin! It's been so long since I saw you!"},
  {who:'B',name:'پریسا Parisa',fa:'پریسا جون! حالت چطوره؟ خانواده‌ات خوبن؟',ro:'Parisā jun! Hālat chetore? Khānevāde-at khuban?',en:'Parisa dear! How are you? Is your family well?'},
  {who:'A',name:'شیرین Shirin',fa:'همه خوبن، ممنون. بابام بازنشسته شد.',ro:'Hame khuban, mamnun. Bābām bāz-nashaste shod.',en:'Everyone is well, thank you. My dad just retired.'},
  {who:'B',name:'پریسا Parisa',fa:'آره؟ ماشاالله! و تو؟ هنوز مجردی؟',ro:'Āre? Māshāllāh! Va to? Hanuz mojradi?',en:'Really? Mashallah! And you? Still single?'},
  {who:'A',name:'شیرین Shirin',fa:'نه، نامزد کردم! ماه دیگه عروسیمه.',ro:'Na, nāmzad kardam! Māh-e dige arusimeh.',en:'No, I got engaged! My wedding is next month!'},
  {who:'B',name:'پریسا Parisa',fa:'مبارک باشه! خوشبخت بشید!',ro:'Mobārak bāshe! Khoshbakht beshid!',en:'Congratulations! May you be happy!'},
]},
vocabSections:[
  {title:'Immediate Family',items:[
    {fa:'پدر',ro:'pedar',en:'father (formal)'},
    {fa:'مادر',ro:'mādar',en:'mother (formal)'},
    {fa:'بابا',ro:'bābā',en:'dad (informal)'},
    {fa:'مامان',ro:'māmān',en:'mum (informal)'},
    {fa:'برادر',ro:'barādar',en:'brother'},
    {fa:'خواهر',ro:'khāhar',en:'sister'},
    {fa:'پسر',ro:'pesar',en:'son / boy'},
    {fa:'دختر',ro:'dokhtar',en:'daughter / girl'},
  ]},
  {title:'Extended Family',items:[
    {fa:'پدربزرگ',ro:'pedar-bozorg',en:'grandfather (paternal)'},
    {fa:'مادربزرگ',ro:'mādar-bozorg',en:'grandmother'},
    {fa:'عمو',ro:"'amu",en:"father's brother (paternal uncle)"},
    {fa:'عمه',ro:"'amme",en:"father's sister (paternal aunt)"},
    {fa:'دایی',ro:'dāyi',en:"mother's brother (maternal uncle)"},
    {fa:'خاله',ro:'khāle',en:"mother's sister (maternal aunt)"},
    {fa:'پسرعمو',ro:"pesar-'amu",en:'male cousin (paternal)'},
    {fa:'نوه',ro:'nave',en:'grandchild'},
  ]},
  {title:'Relationships & Status',items:[
    {fa:'دوست',ro:'dust',en:'friend'},
    {fa:'دوست صمیمی',ro:'dust-e samimi',en:'close friend'},
    {fa:'همسر',ro:'hamsar',en:'spouse (gender-neutral)'},
    {fa:'شوهر',ro:'showhar',en:'husband'},
    {fa:'زن',ro:'zan',en:'wife / woman'},
    {fa:'نامزد',ro:'nāmzad',en:'fiancé / fiancée'},
    {fa:'مجرد',ro:'mojrad',en:'single'},
    {fa:'متأهل',ro:"mota'ahel",en:'married'},
    {fa:'همسایه',ro:'hamsāye',en:'neighbour'},
  ]},
],
culture:{icon:'👨‍👩‍👧',tag:'Family',title:'Family Values in Iranian Culture',
fa:'خانواده',ro:'Khānevāde',en:'"Family"',
body:'Family (خانواده) is the foundation of Iranian society. Multigenerational living is common — grandparents, parents, and children often under one roof. Friday (جمعه) is family day in Iran — when extended family gathers for a large lunch. Addressing elders with شما (you-formal) instead of تو (you-informal) is essential etiquette showing respect.'},
quiz:[
  {q:'مادر means:',c:'مادر',opts:['Father','Sister','Mother','Grandmother'],a:2},
  {q:'مبارک باشه means:',c:'',opts:['Good night','Welcome','Congratulations','Thank you'],a:2},
  {q:'مجرد means:',c:'مجرد',opts:['Married','Divorced','Single','Engaged'],a:2},
  {q:'عمو is your:',c:'عمو',opts:["Mother's brother","Father's brother","Any uncle","Grandfather"],a:1},
  {q:'Using شما instead of تو shows:',c:'',opts:['Anger','Intimacy','Respect/formality','Confusion'],a:2},
]},

{id:'c6',type:'conv',num:'C6',title:'Work & Daily Life',fa:'کار و زندگی روزمره',
intro:"B1 level. Talk about jobs, daily routines, and work life. Iran has a young, highly educated population with a vibrant startup scene — especially in Tehran.",
phrases:[
  {fa:'چیکاره‌ای؟',ro:'Chikāre-i?',en:'What do you do? (informal)'},
  {fa:'مهندسم.',ro:'Mohandesam.',en:"I'm an engineer."},
  {fa:'کجا کار می‌کنی؟',ro:'Kojā kār mikoni?',en:'Where do you work?'},
  {fa:'تو یه شرکت خصوصی کار می‌کنم.',ro:'Tu ye sherkat-e khosousi kār mikonam.',en:'I work in a private company.'},
  {fa:'حقوقت خوبه؟',ro:'Hoghughat khube?',en:'Is your salary good?'},
  {fa:'دورکاری می‌کنم.',ro:'Durkāri mikonam.',en:'I work remotely.'},
],
dialogue:{title:'Meeting at a work conference in Tehran',lines:[
  {who:'A',name:'کاوه Kāveh',fa:'سلام، کاوه‌ام. شما تو این شرکت کار می‌کنید؟',ro:'Salām, Kāveham. Shomā tu in sherkat kār mikonid?',en:'Hi, I\'m Kaveh. Do you work at this company?'},
  {who:'B',name:'نازنین Nāznin',fa:'نه، از یه استارتاپ دیگه اومدم. نازنینم.',ro:'Na, az ye startāp-e dige umadam. Nāzninam.',en:'No, I came from a different startup. I\'m Nazanin.'},
  {who:'A',name:'کاوه Kāveh',fa:'چه کاری می‌کنید؟',ro:'Che kāri mikonid?',en:'What kind of work do you do?'},
  {who:'B',name:'نازنین Nāznin',fa:'برنامه‌نویسم. روی هوش مصنوعی کار می‌کنم.',ro:"Barnāme-nevisam. Ruy-e hushe masnu'i kār mikonam.",en:"I'm a programmer. I work on artificial intelligence."},
  {who:'A',name:'کاوه Kāveh',fa:'جالبه! منم تو حوزه فناوری کار می‌کنم.',ro:'Jālebe! Manam tu howze-ye fanāvari kār mikonam.',en:'Interesting! I also work in the tech field.'},
]},
vocabSections:[
  {title:'Jobs & Professions',items:[
    {fa:'دکتر',ro:'doktor',en:'doctor'},
    {fa:'معلم',ro:"mo'allem",en:'teacher'},
    {fa:'مهندس',ro:'mohandes',en:'engineer'},
    {fa:'برنامه‌نویس',ro:'barnāme-nevis',en:'programmer / developer'},
    {fa:'هنرمند',ro:'honarmand',en:'artist'},
    {fa:'کارمند',ro:'kārmand',en:'employee / clerk'},
    {fa:'دانشجو',ro:'dāneshjoo',en:'university student'},
    {fa:'وکیل',ro:'vakil',en:'lawyer'},
    {fa:'حسابدار',ro:'hesābdār',en:'accountant'},
    {fa:'پرستار',ro:'parastār',en:'nurse'},
  ]},
  {title:'Workplace',items:[
    {fa:'شرکت',ro:'sherkat',en:'company'},
    {fa:'اداره',ro:'edāre',en:'office / government office'},
    {fa:'کارخانه',ro:'kārkhāne',en:'factory'},
    {fa:'بیمارستان',ro:'bimārestān',en:'hospital'},
    {fa:'مدرسه',ro:'madrase',en:'school'},
    {fa:'دانشگاه',ro:'dāneshgāh',en:'university'},
    {fa:'استارتاپ',ro:'startāp',en:'startup'},
    {fa:'دورکاری',ro:'durkāri',en:'remote work'},
  ]},
  {title:'Work Vocabulary',items:[
    {fa:'حقوق',ro:'hoghugh',en:'salary'},
    {fa:'کار',ro:'kār',en:'work / job'},
    {fa:'مرخصی',ro:'morakhasi',en:'leave / vacation'},
    {fa:'جلسه',ro:'jalase',en:'meeting'},
    {fa:'پروژه',ro:'proje',en:'project'},
    {fa:'همکار',ro:'hamkār',en:'colleague'},
    {fa:'رئیس',ro:"ra'is",en:'boss / manager'},
    {fa:'ساعت کاری',ro:"sā'at-e kāri",en:'working hours'},
  ]},
],
culture:{icon:'💼',tag:'Economy',title:"Iran's Young, Tech-Driven Workforce",
fa:'ایران در حال تغییر است.',ro:'Irān dar hāl-e taghyir ast.',en:'"Iran is changing."',
body:"Iran has one of the Middle East's highest university graduation rates, with over 50% of students being women. Tehran has a vibrant startup scene — Iranian engineers and programmers are prominent globally. Despite economic pressures, Iranian youth are highly educated, multilingual, and resourceful."},
quiz:[
  {q:'چیکاره‌ای means:',c:'',opts:['How are you?','What do you do?','Where are you?','When did you come?'],a:1},
  {q:'مهندس means:',c:'مهندس',opts:['Doctor','Teacher','Engineer','Manager'],a:2},
  {q:'دانشجو means:',c:'دانشجو',opts:['Professor','University student','School child','Graduate'],a:1},
  {q:'دورکاری means:',c:'دورکاری',opts:['Overtime','Remote work','Part-time','Commuting'],a:1},
  {q:'What % of Iranian university students are women?',c:'',opts:['About 20%','About 35%','Over 50%','About 45%'],a:2},
]},

// ==================== CULTURE / TRAVEL ====================

{id:'t1',type:'cult',num:'T1',title:'Persian History — Ancient Roots',fa:'تاریخ ایران',
intro:'Iran is one of the world\'s oldest continuous civilizations. From Cyrus the Great to the Islamic Republic, Persian history spans 3,000+ recorded years of empire, art, and intellectual brilliance.',
timeline:[
  {year:'c. 550 BCE',title:'Achaemenid Empire — هخامنشیان',body:'Cyrus the Great (کوروش بزرگ) founded the first Persian Empire. His Cyrus Cylinder is considered the world\'s first human rights declaration. The empire stretched from Greece to India.',fa:'کوروش بزرگ'},
  {year:'330 BCE',title:"Alexander's Conquest — اسکندر",body:'Alexander conquered Persia and burned Persepolis. Yet Persian culture absorbed and transformed its conquerors — as it would do repeatedly throughout history.',fa:'تخت جمشید'},
  {year:'224–651 CE',title:'Sassanid Empire — ساسانیان',body:'The second great Persian empire. Zoroastrianism was the state religion. Persian became a sophisticated literary language. The empire fell to the Arab Islamic conquest in 651 CE.',fa:'زرتشت'},
  {year:'9th–11th c.',title:'Islamic Golden Age — رنسانس ایرانی',body:'Persian scholars led the world in mathematics, astronomy, medicine. Ibn Sina (Avicenna) wrote the Canon of Medicine, used in European universities for 600 years.',fa:'ابن سینا'},
  {year:'1501–1736',title:'Safavid Empire — صفویان',body:'Shah Ismail I established Shia Islam as state religion. Isfahan became one of the world\'s most beautiful cities. Persian art and architecture reached their zenith.',fa:'اصفهان'},
  {year:'1979',title:'Islamic Revolution — انقلاب اسلامی',body:'The Shah was overthrown and the Islamic Republic established. Iran remains the Islamic Republic today — a complex, diverse, and constantly evolving society.',fa:'انقلاب'},
],
culture:{icon:'🏛️',tag:'Heritage',title:'Persepolis — تخت جمشید',
fa:'تخت جمشید، تخت شاهان جهان.',ro:'Takht-e Jamshid, takht-e shāhān-e jahān.',en:'"Persepolis, throne of the kings of the world."',
body:'Persepolis (تخت جمشید) in Fars Province was the ceremonial capital of the Achaemenid Empire, built around 518 BCE. Its carved reliefs show delegations from 23 nations. Burned by Alexander in 330 BCE, its ruins are now a UNESCO World Heritage Site. Every Iranian knows Persepolis as a symbol of civilizational pride.'},
quiz:[
  {q:'Cyrus the Great founded:',c:'',opts:['The Sassanid Empire','The Achaemenid Empire','The Safavid Empire','The Parthian Empire'],a:1},
  {q:'تخت جمشید is:',c:'تخت جمشید',opts:['A city in Tehran','Persepolis','A famous mosque','A mountain peak'],a:1},
  {q:'The Safavid Empire established which religion as state religion?',c:'',opts:['Sunni Islam','Zoroastrianism','Shia Islam','Christianity'],a:2},
  {q:'Ibn Sina (Avicenna) was famous for:',c:'',opts:['Poetry','Mathematics only','Medicine and philosophy','Architecture'],a:2},
  {q:'The Islamic Revolution in Iran was in:',c:'',opts:['1953','1963','1979','1989'],a:2},
]},

{id:'t2',type:'cult',num:'T2',title:'Famous Cities — Tehran & Isfahan',fa:'تهران و اصفهان',
intro:'Iran\'s two most iconic cities: Tehran, the vast modern capital, and Isfahan, the jewel of Safavid architecture. Each has its own unmistakable soul.',
cities:[
  {name:'Tehran',fa:'تهران',desc:'Capital and megacity of 15+ million. The Alborz mountains frame its northern skyline with ski slopes visible year-round. A city of traffic, culture, incredible food, and palpable energy.',sights:'Milad Tower · Golestan Palace · Grand Bazaar · Darband hiking trail · Tehran Museum of Contemporary Art'},
  {name:'Isfahan',fa:'اصفهان',desc:'"Isfahan is half the world" (اصفهان نصف جهان). The Safavid capital features the world\'s most beautiful central square — Naqsh-e Jahan, UNESCO-listed.',sights:'Naqsh-e Jahan Square · Sheikh Lotfallah Mosque · Khaju Bridge · Vank Cathedral · Si-o-Se Pol bridge'},
],
sightPhrases:[
  {fa:'کجا هستیم؟',ro:'Kojā hastim?',en:'Where are we?'},
  {fa:'این بنا مال کِی‌ه؟',ro:'In banā māl-e kihe?',en:'What era is this building from?'},
  {fa:'بلیط چند تومانه؟',ro:'Belit chand tomāne?',en:'How much is the ticket?'},
  {fa:'این مسجد واقعاً باشکوهه.',ro:"In masjed vāqe'an bāshokohe.",en:'This mosque is truly magnificent.'},
],
culture:{icon:'🕌',tag:'Architecture',title:'Naqsh-e Jahan Square — نقش جهان',
fa:'اصفهان نصف جهان است.',ro:'Esfahān nesf-e jahān ast.',en:'"Isfahan is half the world."',
body:'Naqsh-e Jahan ("Image of the World") Square was built by Shah Abbas I around 1602. At 512m × 163m, it is one of the world\'s largest public squares. The tilework uses a mathematical mosaic system predating Western computer graphics. Polo was played here — the goalposts still stand. UNESCO World Heritage Site since 1979.'},
quiz:[
  {q:'اصفهان نصف جهان means:',c:'',opts:['Isfahan is the capital','Isfahan is half the world','Isfahan is ancient','Isfahan is beautiful'],a:1},
  {q:'Tehran has approximately:',c:'',opts:['3 million','8 million','15+ million','25 million'],a:2},
  {q:'Naqsh-e Jahan Square was built by:',c:'',opts:['Cyrus the Great','Shah Abbas I','Rumi','Hafez'],a:1},
  {q:'بلیط چند تومانه means:',c:'',opts:['Where is the entrance?','How much is the ticket?','When does it open?','Is it UNESCO listed?'],a:1},
  {q:'Which sport was historically played at Naqsh-e Jahan?',c:'',opts:['Wrestling','Archery','Polo','Football'],a:2},
]},

{id:'t3',type:'cult',num:'T3',title:'Famous Cities — Shiraz & Persepolis',fa:'شیراز و تخت جمشید',
intro:'Shiraz is the city of poets, roses, and gardens. Nearby lies Persepolis — the greatest surviving monument of ancient Persia. Together they form the essential cultural journey of the south.',
cities:[
  {name:'Shiraz',fa:'شیراز',desc:'City of Hafez and Saadi — Iran\'s two greatest lyric poets. Famous for its roses, gardens, and the spectacular Pink Mosque. Warm, laid-back, and strikingly beautiful.',sights:'Tomb of Hafez · Tomb of Saadi · Nasir-ol-Molk (Pink) Mosque · Eram Garden · Vakil Bazaar'},
  {name:'Persepolis',fa:'تخت جمشید',desc:'50km northeast of Shiraz. The Achaemenid ceremonial capital, built 518 BCE and burned by Alexander in 330 BCE. Giant carved columns, bas-reliefs of subject nations, the Gate of All Nations.',sights:'Gate of All Nations · Apadana Palace · Hall of 100 Columns · Treasury · Naqsh-e Rostam royal tombs'},
],
sightPhrases:[
  {fa:'مقبره حافظ کجاست؟',ro:'Maqbare-ye Hāfez kojāst?',en:'Where is the tomb of Hafez?'},
  {fa:'چقدر باشکوهه!',ro:'Cheghadr bāshokohe!',en:'How magnificent it is!'},
  {fa:'عکس بگیریم؟',ro:'Aks begirim?',en:'Shall we take a photo?'},
  {fa:'تاریخ ایران خیلی غنیه.',ro:'Tārikh-e Irān kheyly ghanihe.',en:'Iranian history is very rich.'},
],
culture:{icon:'📖',tag:'Poetry',title:'Hafez — The Tongue of the Unseen',
fa:'الا یا ایها الساقی ادر کأساً و ناولها.',ro:"Alā yā ayyohā as-sāqi adir ka'san wa nāwilhā.",en:'"Come, O Cupbearer, pass the cup around..."',
body:'Hafez (حافظ, 1315–1390) of Shiraz is Iran\'s greatest lyric poet. His Divan is found in virtually every Iranian home — used for فال حافظ (fāl-e Hāfez): opening randomly for spiritual guidance. His tomb in Shiraz\'s Hafezieh garden is one of Iran\'s most visited sites.'},
quiz:[
  {q:'Hafez was from:',c:'',opts:['Tehran','Isfahan','Shiraz','Tabriz'],a:2},
  {q:'فال حافظ is:',c:'',opts:['A food dish','Opening the Divan for guidance','A music tradition','A dance'],a:1},
  {q:'Persepolis was built approximately:',c:'',opts:['100 BCE','518 BCE','200 CE','1000 CE'],a:1},
  {q:'چقدر باشکوهه means:',c:'',opts:['How old is it?','How far is it?','How magnificent!','How expensive!'],a:2},
  {q:'The "Pink Mosque" is in:',c:'',opts:['Tehran','Isfahan','Shiraz','Tabriz'],a:2},
]},

{id:'t4',type:'cult',num:'T4',title:'Weather & Seasons in Iran',fa:'آب و هوای ایران',
intro:'Iran is a vast country with dramatically different climates — from ski slopes north of Tehran to beach resorts on the Persian Gulf, and vast deserts in between.',
seasons:[
  {icon:'🌸',s:'Spring — بهار',r:'bahār',temp:'10–25°C',desc:'Best travel season. Nowruz in March. Gardens bloom, waterfalls flow. The whole country is on the move.'},
  {icon:'☀️',s:'Summer — تابستان',r:'tābestan',temp:'25–45°C',desc:'Very hot in most cities. Iranians escape to the Caspian coast or mountain villages. The north stays pleasant.'},
  {icon:'🍂',s:'Autumn — پاییز',r:'pāyiz',temp:'8–22°C',desc:'Beautiful and mild. Pomegranates ripen. Second-best travel season — fewer crowds than spring.'},
  {icon:'❄️',s:'Winter — زمستان',r:'zemestān',temp:'-5 to 15°C',desc:'Ski season! Dizin and Shemshak near Tehran have world-class slopes. Desert towns stay mild and perfect for visiting.'},
],
weatherPhrases:[
  {fa:'هوا چطوره؟',ro:'Havā chetore?',en:"How's the weather?"},
  {fa:'باران می‌آد.',ro:'Bārān miyād.',en:"It's raining."},
  {fa:'هوا ابریه.',ro:'Havā abrihe.',en:"It's cloudy."},
  {fa:'گرمای طاقت‌فرساست.',ro:'Garmā-ye tāqat-forsāst.',en:"It's unbearably hot."},
  {fa:'برف می‌آد.',ro:'Barf miyād.',en:"It's snowing."},
  {fa:'هوا عالیه!',ro:'Havā ālihe!',en:'The weather is perfect!'},
],
culture:{icon:'🌷',tag:'Season',title:'Nowruz — نوروز — The Persian New Year',
fa:'بهار که آمد، دل شادمان شد.',ro:'Bahār ke āmad, del shādmān shod.',en:'"When spring came, the heart became joyful."',
body:"Nowruz (نوروز — 'New Day') is the Persian New Year, celebrated on the Spring Equinox. 3,000 years old, predating Islam. The Haft-Seen table (هفت‌سین) must have seven items starting with 'س': sprouted wheat, apple, wheat pudding, vinegar, dried lotus fruit, coins, garlic. The 13th day (Sizdah-be-dar) everyone must go outdoors — staying home brings bad luck."},
quiz:[
  {q:'بهار means:',c:'بهار',opts:['Summer','Spring','Autumn','Winter'],a:1},
  {q:'Nowruz falls on:',c:'',opts:['January 1','The Winter Solstice','The Spring Equinox','March 1'],a:2},
  {q:'برف می‌آد means:',c:'',opts:["It's raining","It's sunny","It's snowing","It's windy"],a:2},
  {q:'The Haft-Seen table has items starting with:',c:'',opts:['الف (A)','ب (B)','س (S)','م (M)'],a:2},
  {q:'زمستان means:',c:'زمستان',opts:['Spring','Summer','Autumn','Winter'],a:3},
]},

{id:'t5',type:'cult',num:'T5',title:'Travel Tips & Practical Persian',fa:'راهنمای سفر',
intro:'B1 practical Persian for travellers. Get around, stay safe, and connect with locals. Iranians are famously among the warmest hosts in the world.',
tips:[
  {icon:'🛂',title:'Visa & Entry',body:'Most nationalities need a visa. Tourist visas are often issued on arrival at major airports. Always check current requirements before travelling.'},
  {icon:'💰',title:'Money',body:'International cards do not work in Iran — bring cash (Euros or USD are best). Prices are quoted in Tomans. Exchange at hotels or authorised offices.'},
  {icon:'👗',title:'Dress Code',body:'Women must wear hijab (حجاب) in public — a headscarf plus loose clothing. Men should avoid shorts in formal or religious settings.'},
  {icon:'📱',title:'Communications',body:'VPN is widely used. Local SIM cards are cheap at the airport. WiFi is common in hotels and cafés.'},
  {icon:'🚕',title:'Getting Around',body:'Tehran has a modern metro (مترو). Snapp (Iranian Uber) works in major cities. Intercity buses are comfortable. Trains are scenic and affordable.'},
  {icon:'🏥',title:'Safety',body:'Iran is generally very safe for tourists. Locals often go out of their way to help — expect invitations to tea and meals from strangers!'},
],
travelPhrases:[
  {fa:'کمکم کنید لطفاً.',ro:'Komakam konid lotfan.',en:'Please help me.'},
  {fa:'گم شدم.',ro:'Gom shodam.',en:"I'm lost."},
  {fa:'بیمارستان کجاست؟',ro:'Bimārestān kojāst?',en:'Where is the hospital?'},
  {fa:'متشکرم.',ro:'Motashakkeram.',en:'Thank you (formal).'},
  {fa:'کمی فارسی بلدم.',ro:'Kami Fārsi balad-am.',en:'I know a little Persian.'},
  {fa:'ایران خیلی زیباست.',ro:'Irān kheyly zibāst.',en:'Iran is very beautiful.'},
],
culture:{icon:'✈️',tag:'Traveller Tips',title:'Iranians & Foreign Visitors',
fa:'خوش آمدید!',ro:'Khosh āmadid!',en:'"Welcome!"',
body:"Iran consistently surprises first-time visitors with the warmth of its people. Strangers invite you for tea, insist on paying for your meal, offer to show you around. Learning even a few Persian words creates instant goodwill. The most important phrase: ایران خیلی زیباست — 'Iran is very beautiful!'"},
quiz:[
  {q:'گم شدم means:',c:'گم شدم',opts:["I'm tired","I'm hungry","I'm lost","I'm late"],a:2},
  {q:'In Iran, prices are quoted in:',c:'',opts:['Rials','Dollars','Tomans','Euros'],a:2},
  {q:'Women travellers in Iran must wear:',c:'',opts:['Full niqab','Hijab (headscarf + loose clothing)','Nothing specific','A chador only'],a:1},
  {q:'خوش آمدید means:',c:'',opts:['Goodbye','Thank you','Welcome','Good morning'],a:2},
  {q:'متشکرم is:',c:'متشکرم',opts:['Informal thank you','Formal thank you','Please','Sorry'],a:1},
]},

]; // end LESSONS
