const COLORS=['#c8703a','#5b9bd5','#6baa7a','#9b7fc8','#d4a843'];

const LESSONS = [

// ==================== ALPHABET ====================
{id:'a1',type:'alpha',num:'A1',title:'Alef · Be · Pe · Te · Se',fa:'ا ب پ ت ث',
intro:'Welcome to Persian! We start with the first five letters. Persian reads right to left, and most letters connect to each other like cursive.',
chars:[
  {l:'ا',n:'Alef',r:'ā / a',d:'Like "a" in father. Alef is a vowel carrier and does NOT connect to the next letter.',nc:true},
  {l:'ب',n:'Be',r:'b',d:'Like "b" in book. One dot below the baseline.'},
  {l:'پ',n:'Pe',r:'p',d:'Like "p" in pen. Three dots below — Persian\'s own letter, not in Arabic!'},
  {l:'ت',n:'Te',r:'t',d:'Like "t" in ten. Two dots above.'},
  {l:'ث',n:'Se',r:'s',d:'Like "s" in sun. Three dots above. Rare in modern Farsi words.'},
],
forms:[
  {c:'ا',n:'Alef',s:'ا',i:'اَ',m:'ـا',f:'ـا',nc:true,tip:'Alef NEVER connects to the letter on its left.'},
  {c:'ب',n:'Be',s:'ب',i:'بـ',m:'ـبـ',f:'ـب'},
  {c:'پ',n:'Pe',s:'پ',i:'پـ',m:'ـپـ',f:'ـپ'},
  {c:'ت',n:'Te',s:'ت',i:'تـ',m:'ـتـ',f:'ـت'},
  {c:'ث',n:'Se',s:'ث',i:'ثـ',m:'ـثـ',f:'ـث'},
],
vocab:[
  {fa:'آب',ro:'āb',en:'water'},{fa:'بابا',ro:'bābā',en:'dad/father'},{fa:'تاب',ro:'tāb',en:'swing/light'},
  {fa:'پِدَر',ro:'pedar',en:'father (formal)'},{fa:'باب',ro:'bāb',en:'door/chapter'},
],
sentences:[
  {fa:'بابا آب داد.',ro:'Bābā āb dād.',en:'Dad gave water. (The classic Persian primer sentence!)'},
  {fa:'آب تاب دارد.',ro:'Āb tāb dārad.',en:'The water shines.'},
],
culture:{icon:'📜',tag:'Primer',title:'The Sentence Every Iranian Child Reads First',
fa:'بابا آب داد.',ro:'Bābā āb dād.',en:'"Dad gave water."',
body:'For over a century, this three-word sentence has opened every Persian literacy primer. Simple letters, deep tenderness. Water (آب) holds sacred status in Persian culture — it means generosity, life, purity. Rivers, fountains, and reflecting pools run through Persian gardens, poetry, and architecture.'},
quiz:[
  {q:'Name this letter:',c:'ب',opts:['Alef','Be','Pe','Te'],a:1},
  {q:'Which letter does NOT connect leftward?',c:'',opts:['ب Be','پ Pe','ا Alef','ت Te'],a:2},
  {q:'آب means:',c:'آب',opts:['Fire','Water','Earth','Wind'],a:1},
  {q:'Pe (پ) has how many dots?',c:'پ',opts:['One below','Two above','Three below','None'],a:2},
  {q:'پِدَر means:',c:'پِدَر',opts:['Mother','Brother','Father','Child'],a:2},
]},

{id:'a2',type:'alpha',num:'A2',title:'Jim · Che · He · Khe · Dal',fa:'ج چ ح خ د',
intro:'Five more letters. Notice how ج چ ح خ all share the same body — only their dots differ! And Dal is another non-connector.',
chars:[
  {l:'ج',n:'Jim',r:'j',d:'Like "j" in jar. Dot below the curve.'},
  {l:'چ',n:'Che',r:'ch',d:'Like "ch" in chair. Three dots below. Persian\'s own!'},
  {l:'ح',n:'He (Jimi)',r:'h',d:'Breathy "h". Same shape as Jim/Che but NO dots.'},
  {l:'خ',n:'Khe',r:'kh',d:'Guttural like Scottish "loch". One dot above.'},
  {l:'د',n:'Dal',r:'d',d:'Like "d" in door. Does NOT connect to next letter.',nc:true},
],
forms:[
  {c:'ج',n:'Jim',s:'ج',i:'جـ',m:'ـجـ',f:'ـج'},
  {c:'چ',n:'Che',s:'چ',i:'چـ',m:'ـچـ',f:'ـچ'},
  {c:'ح',n:'He',s:'ح',i:'حـ',m:'ـحـ',f:'ـح'},
  {c:'خ',n:'Khe',s:'خ',i:'خـ',m:'ـخـ',f:'ـخ'},
  {c:'د',n:'Dal',s:'د',i:'دـ',m:'ـد',f:'ـد',nc:true,tip:'Dal does NOT connect to the next letter.'},
],
vocab:[
  {fa:'جان',ro:'jān',en:'soul / dear one'},{fa:'چای',ro:'chāy',en:'tea'},{fa:'دَر',ro:'dar',en:'door / in'},
  {fa:'خانه',ro:'khāne',en:'house / home'},{fa:'باد',ro:'bād',en:'wind'},
],
sentences:[
  {fa:'چای داری؟',ro:'Chāy dāri?',en:'Do you have (any) tea?'},
  {fa:'خانه‌ام جادار است.',ro:'Khāne-am jādār ast.',en:'My house is spacious.'},
],
culture:{icon:'🍵',tag:'Culture',title:'چای — Tea & Persian Hospitality',
fa:'چای نخوردی؟',ro:'Chāy nakhordī?',en:'"Haven\'t you had tea yet?"',
body:'Offering tea (چای) is the first act of Persian hospitality. A host who hasn\'t offered tea has not truly welcomed you. Persian tea is brewed strong in a small glass (استکان estekān), often taken with rock sugar (نبات nabāt) held between the teeth while sipping. Refusing tea can feel like refusing friendship itself.'},
quiz:[
  {q:'چ sounds like:',c:'چ',opts:['"j" in jar','"ch" in chair','"kh" in loch','"h" breathy'],a:1},
  {q:'Which does NOT connect leftward?',c:'',opts:['ج Jim','چ Che','ح He','د Dal'],a:3},
  {q:'خانه means:',c:'خانه',opts:['Tea','Door','Home','Soul'],a:2},
  {q:'چای means:',c:'چای',opts:['Coffee','Water','Tea','Milk'],a:2},
  {q:'Khe (خ) sounds like:',c:'خ',opts:['"k" in key','"ch" in chair','Scottish "ch" in loch','"h" in hat'],a:2},
]},

{id:'a3',type:'alpha',num:'A3',title:'Zal · Re · Ze · Zhe · Sin',fa:'ذ ر ز ژ س',
intro:'Four non-connectors in one lesson! The Re family all sit below the line and sweep right. Sin has three distinctive "teeth" on top.',
chars:[
  {l:'ذ',n:'Zal',r:'z',d:'Like "z" in zone. Does NOT connect left.',nc:true},
  {l:'ر',n:'Re',r:'r',d:'A flapped/rolled "r". Does NOT connect left.',nc:true},
  {l:'ز',n:'Ze',r:'z',d:'Like "z" in zone. Does NOT connect left.',nc:true},
  {l:'ژ',n:'Zhe',r:'zh',d:'Like "s" in measure or French "j". Does NOT connect left.',nc:true},
  {l:'س',n:'Sin',r:'s',d:'Like "s" in sea. Three teeth on top. Connects.'},
],
forms:[
  {c:'ذ',n:'Zal',s:'ذ',i:'ذ',m:'ـذ',f:'ـذ',nc:true,tip:'Does NOT connect left.'},
  {c:'ر',n:'Re',s:'ر',i:'ر',m:'ـر',f:'ـر',nc:true,tip:'Does NOT connect left.'},
  {c:'ز',n:'Ze',s:'ز',i:'ز',m:'ـز',f:'ـز',nc:true,tip:'Does NOT connect left.'},
  {c:'ژ',n:'Zhe',s:'ژ',i:'ژ',m:'ـژ',f:'ـژ',nc:true,tip:'Does NOT connect left.'},
  {c:'س',n:'Sin',s:'س',i:'سـ',m:'ـسـ',f:'ـس'},
],
vocab:[
  {fa:'سَر',ro:'sar',en:'head'},{fa:'زَر',ro:'zar',en:'gold'},{fa:'سَرد',ro:'sard',en:'cold'},
  {fa:'رَز',ro:'raz',en:'grapevine / secret'},{fa:'دَرس',ro:'dars',en:'lesson'},
],
sentences:[
  {fa:'هوا سرد است.',ro:'Havā sard ast.',en:'The weather is cold.'},
  {fa:'دَرس یاد می‌گیرم.',ro:'Dars yād migiram.',en:'I am learning a lesson.'},
],
culture:{icon:'🌹',tag:'Poetry',title:'Rumi — Master of Persian Verse',
fa:'بشنو این نی چون شکایت می‌کند.',ro:'Beshno in ney chon shekāyat mikonad.',en:'"Listen to the reed, how it tells a tale of separation."',
body:'These are the opening words of the Masnavi by Rūmī (1207–1273), one of the most widely read poets in history. The ney (نی) is a reed flute — a metaphor for the soul separated from its source, longing to return. Notice how the rolling Re (ر) flows through this verse like water. Rumi wrote in Persian even while living in what is now Turkey.'},
quiz:[
  {q:'How many non-connectors are in this lesson?',c:'',opts:['2','3','4','5'],a:2},
  {q:'ژ (Zhe) sounds like:',c:'ژ',opts:['"z" in zone','"s" in measure','"ch" in chair','"r" in run'],a:1},
  {q:'سَرد means:',c:'سَرد',opts:['Hot','Cold','Rain','Wind'],a:1},
  {q:'Sin (س) has how many teeth?',c:'س',opts:['One','Two','Three','Four'],a:2},
  {q:'زَر means:',c:'زَر',opts:['Silver','Gold','Copper','Iron'],a:1},
]},

{id:'a4',type:'alpha',num:'A4',title:'Shin · Sad · Zad · Ta · Za',fa:'ش ص ض ط ظ',
intro:'Shin is Sin with three dots above. Sad, Zad, Ta, Za are "emphatic" letters — they sound heavier, coming from deeper in the mouth.',
chars:[
  {l:'ش',n:'Shin',r:'sh',d:'Like "sh" in shoe. Three dots above Sin\'s body.'},
  {l:'ص',n:'Sad',r:'s (emphatic)',d:'Heavier "s" — a loop with a small tooth. From Arabic script.'},
  {l:'ض',n:'Zad',r:'z (emphatic)',d:'Heavier "z". One dot above Sad\'s shape.'},
  {l:'ط',n:'Ta (Tarsim)',r:'t (emphatic)',d:'Heavier "t". A tall vertical stroke on a loop.'},
  {l:'ظ',n:'Za (Moajame)',r:'z (emphatic)',d:'Heavier "z". One dot above Ta.'},
],
forms:[
  {c:'ش',n:'Shin',s:'ش',i:'شـ',m:'ـشـ',f:'ـش'},
  {c:'ص',n:'Sad',s:'ص',i:'صـ',m:'ـصـ',f:'ـص'},
  {c:'ض',n:'Zad',s:'ض',i:'ضـ',m:'ـضـ',f:'ـض'},
  {c:'ط',n:'Ta',s:'ط',i:'طـ',m:'ـطـ',f:'ـط'},
  {c:'ظ',n:'Za',s:'ظ',i:'ظـ',m:'ـظـ',f:'ـظ'},
],
vocab:[
  {fa:'شَب',ro:'shab',en:'night'},{fa:'شادی',ro:'shādi',en:'happiness'},{fa:'صَبا',ro:'sabā',en:'morning breeze'},
  {fa:'طَبیب',ro:'tabib',en:'doctor'},{fa:'شب بخیر',ro:'shab bekheyr',en:'good night'},
],
sentences:[
  {fa:'شب بخیر.',ro:'Shab bekheyr.',en:'Good night.'},
  {fa:'شادی بخش باد.',ro:'Shādi bakhsh bād.',en:'May it bring joy.'},
],
culture:{icon:'🎨',tag:'Art',title:'Persian Miniature Painting',
fa:'نگارگری ایرانی',ro:'Negārgari-ye Irāni',en:'"Persian Painting"',
body:'Persian miniature painting (نگارگری) developed from the 13th century. These jewel-like works illustrate epic poetry — especially the Shahnameh (Book of Kings) by Ferdowsi. Artists used lapis lazuli blues, gold leaf, and impossible detail to portray gardens, battles, and romance. Safavid court painters of Isfahan (16th–17th c.) were the masters. Night scenes — شَب (shab) — gardens under moonlight — are a recurring, beloved theme.'},
quiz:[
  {q:'Shin (ش) differs from Sin (س) by:',c:'ش',opts:['One dot below','Two dots','Three dots above','A loop'],a:2},
  {q:'شَب means:',c:'شَب',opts:['Morning','Noon','Evening','Night'],a:3},
  {q:'شب بخیر means:',c:'شب بخیر',opts:['Good morning','Good night','Hello','Goodbye'],a:1},
  {q:'Which has a dot above the Ta shape?',c:'',opts:['ش Shin','ص Sad','ط Ta','ظ Za'],a:3},
  {q:'شادی means:',c:'شادی',opts:['Sadness','Anger','Happiness','Fear'],a:2},
]},

{id:'a5',type:'alpha',num:'A5',title:'Ain · Ghain · Fe · Qaf · Kaf',fa:'ع غ ف ق ک',
intro:'Ain is the most distinctive sound in Persian — a voiced pharyngeal with no English equivalent. Ghain is Ain with a dot. Fe, Qaf, Kaf are more familiar.',
chars:[
  {l:'ع',n:'Ain',r:"'",d:"A unique guttural from the throat. No English equivalent — a constriction in the pharynx."},
  {l:'غ',n:'Ghain',r:'gh',d:'A gargling sound, like a French "r". One dot above Ain.'},
  {l:'ف',n:'Fe',r:'f',d:'Like "f" in fun. One dot above a curved body.'},
  {l:'ق',n:'Qaf',r:'q',d:'A deep "k" from the back of the throat. Two dots above.'},
  {l:'ک',n:'Kaf',r:'k',d:'Like "k" in key. Distinctive diagonal stroke inside.'},
],
forms:[
  {c:'ع',n:'Ain',s:'ع',i:'عـ',m:'ـعـ',f:'ـع'},
  {c:'غ',n:'Ghain',s:'غ',i:'غـ',m:'ـغـ',f:'ـغ'},
  {c:'ف',n:'Fe',s:'ف',i:'فـ',m:'ـفـ',f:'ـف'},
  {c:'ق',n:'Qaf',s:'ق',i:'قـ',m:'ـقـ',f:'ـق'},
  {c:'ک',n:'Kaf',s:'ک',i:'کـ',m:'ـکـ',f:'ـک'},
],
vocab:[
  {fa:'عَشق',ro:"'eshq",en:'love / passion'},{fa:'کِتاب',ro:'ketāb',en:'book'},{fa:'غَم',ro:'gham',en:'sorrow'},
  {fa:'فارسی',ro:'Fārsi',en:'the Persian language'},{fa:'عکس',ro:"'aks",en:'photo / image'},
],
sentences:[
  {fa:'کِتاب دارم.',ro:'Ketāb dāram.',en:'I have a book.'},
  {fa:'عشق زندگی است.',ro:"'Eshq zendegi ast.",en:'Love is life.'},
],
culture:{icon:'💫',tag:'Proverb',title:'Drop by Drop — A Persian Proverb',
fa:'قطره قطره دریا می‌شود.',ro:'Qatre qatre daryā mishavad.',en:'"Drop by drop, it becomes a sea."',
body:'This beloved proverb encourages perseverance. Every vocabulary word you memorize, every letter you practise — slowly becomes an ocean of knowledge. قطره (qatre) = drop · دریا (daryā) = sea. The Caspian Sea bordering northern Iran is called دریای خزر (Daryā-ye Khazar). This proverb is perfect for your journey learning فارسی!'},
quiz:[
  {q:'عَشق means:',c:'عَشق',opts:['Sorrow','Joy','Love','Anger'],a:2},
  {q:'Ghain (غ) is Ain (ع) plus:',c:'غ',opts:['No dots','One dot above','Two dots','Three dots'],a:1},
  {q:'کِتاب means:',c:'کِتاب',opts:['Pen','Paper','Notebook','Book'],a:3},
  {q:'Fe (ف) sounds like:',c:'ف',opts:['"v" in van','"f" in fun','"p" in pen','"b" in bat'],a:1},
  {q:'فارسی means:',c:'فارسی',opts:['Iran','Arabic','The Persian language','A city'],a:2},
]},

{id:'a6',type:'alpha',num:'A6',title:'Gaf · Lam · Mim · Nun · Vav',fa:'گ ل م ن و',
intro:'Gaf is the Persian "g" — not found in Arabic. Lam, Mim, Nun are very common. Vav serves as both a consonant and a long vowel.',
chars:[
  {l:'گ',n:'Gaf',r:'g',d:'Like "g" in go. Persian\'s own letter — not in Arabic! Two diagonal strokes on Kaf\'s body.'},
  {l:'ل',n:'Lam',r:'l',d:'Like "l" in love. A tall upward stroke that curves to connect.'},
  {l:'م',n:'Mim',r:'m',d:'Like "m" in moon. A small circle with a tail.'},
  {l:'ن',n:'Nun',r:'n',d:'Like "n" in now. A bowl shape with one dot above.'},
  {l:'و',n:'Vav',r:'v / ow / u',d:'Like "v" in vine OR long "o"/"u". Does NOT connect left.',nc:true},
],
forms:[
  {c:'گ',n:'Gaf',s:'گ',i:'گـ',m:'ـگـ',f:'ـگ'},
  {c:'ل',n:'Lam',s:'ل',i:'لـ',m:'ـلـ',f:'ـل'},
  {c:'م',n:'Mim',s:'م',i:'مـ',m:'ـمـ',f:'ـم'},
  {c:'ن',n:'Nun',s:'ن',i:'نـ',m:'ـنـ',f:'ـن'},
  {c:'و',n:'Vav',s:'و',i:'و',m:'ـو',f:'ـو',nc:true,tip:'Vav does NOT connect to the next letter.'},
],
vocab:[
  {fa:'مادر',ro:'mādar',en:'mother'},{fa:'نان',ro:'nān',en:'bread'},{fa:'گل',ro:'gol',en:'flower / rose'},
  {fa:'نام',ro:'nām',en:'name'},{fa:'لال',ro:'lāl',en:'silent / mute'},{fa:'من',ro:'man',en:'I / me'},
],
sentences:[
  {fa:'نام من لیلاست.',ro:'Nām-e man Laylāst.',en:'My name is Layla.'},
  {fa:'گل زیباست.',ro:'Gol zibāst.',en:'The flower is beautiful.'},
],
culture:{icon:'🌺',tag:'Symbol',title:'گل — The Rose in Persian Culture',
fa:'گل بی‌خار نمی‌شود.',ro:'Gol bi-khār nemishavad.',en:'"A rose does not grow without thorns."',
body:'The rose (گل) and the nightingale (بلبل bulbul) are the two great symbols of Persian poetry. The rose represents beauty, the beloved, and divine love. The nightingale weeps for the rose — representing the lover longing for the unattainable beloved. This pairing appears in Hafez, Rumi, and hundreds of classical poets. When you give flowers in Iran, odd numbers only — even numbers are for funerals.'},
quiz:[
  {q:'Gaf (گ) differs from Kaf (ک) by:',c:'گ',opts:['One dot below','Two diagonal strokes added','Three dots above','A loop'],a:1},
  {q:'Vav (و) is a non-connector?',c:'و',opts:['True','False'],a:0},
  {q:'مادر means:',c:'مادر',opts:['Father','Sister','Mother','Brother'],a:2},
  {q:'نان means:',c:'نان',opts:['Water','Tea','Bread','Rice'],a:2},
  {q:'من means:',c:'من',opts:['You','He/She','I / me','We'],a:2},
]},

{id:'a7',type:'alpha',num:'A7',title:'He · Ye — Final Letters!',fa:'ه ی',
intro:'The last two letters of the Persian alphabet! He is tricky — it changes shape a lot. Ye is the long "ee" vowel and also the "y" consonant. You now know all 32 letters!',
chars:[
  {l:'ه',n:'He (Havvaz)',r:'h',d:'Like "h" in hat. Changes shape a lot: standalone ه, initial هـ, medial ـهـ, final ـه or ـ‌ه.'},
  {l:'ی',n:'Ye',r:'y / i',d:'Like "y" in yes OR long "ee". Very common — also an ezāfe connector.'},
],
forms:[
  {c:'ه',n:'He',s:'ه',i:'هـ',m:'ـهـ',f:'ـه / ه‌',nc:false},
  {c:'ی',n:'Ye',s:'ی',i:'یـ',m:'ـیـ',f:'ـی'},
],
vocab:[
  {fa:'هَر',ro:'har',en:'every / each'},{fa:'یاد',ro:'yād',en:'memory / learning'},{fa:'هوا',ro:'havā',en:'weather / air'},
  {fa:'ایران',ro:'Irān',en:'Iran'},{fa:'زیبا',ro:'zibā',en:'beautiful'},{fa:'خوب',ro:'khub',en:'good'},
],
sentences:[
  {fa:'ایران زیباست.',ro:'Irān zibāst.',en:'Iran is beautiful.'},
  {fa:'هوا خوب است.',ro:'Havā khub ast.',en:'The weather is good.'},
  {fa:'یاد بگیر!',ro:'Yād begir!',en:'Learn! (Take it to memory!)'},
],
culture:{icon:'🎉',tag:'Milestone',title:'شما الفبا را یاد گرفتید! — You Learned the Alphabet!',
fa:'مبارک باشد!',ro:'Mobārak bāshad!',en:'"Congratulations!"',
body:'You now know all 32 letters of the Persian alphabet (الفبا, alefbā). The name comes from the first two letters: الف (Alef) + ب (Be). Persian uses the Arabic script but has 4 extra letters: پ چ ژ گ. Now you can sound out any Persian word, even if you don\'t know its meaning yet. This is a huge milestone! As Iranians say: قدم به قدم — qadam be qadam — step by step.'},
quiz:[
  {q:'How many letters does the Persian alphabet have?',c:'',opts:['26','28','32','36'],a:2},
  {q:'Which 4 letters exist in Persian but NOT Arabic?',c:'',opts:['ب پ ت ث','پ چ ژ گ','ج چ ح خ','ک گ ل م'],a:1},
  {q:'هوا means:',c:'هوا',opts:['Water','Air/Weather','Earth','Fire'],a:1},
  {q:'مبارک باشد means:',c:'مبارک باشد',opts:['Good night','Thank you','Congratulations','Welcome'],a:2},
  {q:'Ye (ی) can be:',c:'ی',opts:['Only consonant "y"','Only vowel "ee"','Both consonant and long vowel','Neither'],a:2},
]},

// ==================== CONVERSATIONAL ====================
{id:'c1',type:'conv',num:'C1',title:'Greetings & Introductions',fa:'سلام و آشنایی',
intro:'A1 level. Learn to say hello, introduce yourself, ask names, and use basic courtesy phrases. Iranians greet warmly — expect handshakes, sometimes cheek kisses among close friends.',
phrases:[
  {fa:'سلام',ro:'Salām',en:'Hello'},
  {fa:'خوبی؟',ro:'Khuby?',en:'Are you well? (informal)'},
  {fa:'خوبم، ممنون.',ro:'Khubam, mamnun.',en:'I\'m well, thank you.'},
  {fa:'اسمت چیه؟',ro:'Esmat chiye?',en:'What\'s your name? (informal)'},
  {fa:'اسمم ... است.',ro:'Esmam ... ast.',en:'My name is ...'},
  {fa:'از آشنایی‌تون خوشحالم.',ro:'Az āshnāyi-tun khushhālam.',en:'Pleased to meet you.'},
  {fa:'خداحافظ.',ro:'Khodāhāfez.',en:'Goodbye (formal)'},
  {fa:'بعداً می‌بینمت.',ro:'Ba\'dan mibinamat.',en:'See you later.'},
],
dialogue:{title:'First meeting at a café in Tehran',
lines:[
  {who:'A',name:'سارا Sara',fa:'سلام! اسمم ساراست. اسم تو چیه؟',ro:'Salām! Esmam Sārāst. Esm-e to chiye?',en:'Hi! My name is Sara. What\'s your name?'},
  {who:'B',name:'رضا Rezā',fa:'سلام سارا! منم رضام. خوشوقتم.',ro:'Salām Sārā! Manam Rezām. Khoshvagtam.',en:'Hi Sara! I\'m Reza too. Nice to meet you.'},
  {who:'A',name:'سارا Sara',fa:'از کجایی، رضا؟',ro:'Az kojāyi, Rezā?',en:'Where are you from, Reza?'},
  {who:'B',name:'رضا Rezā',fa:'از تهرانم. تو چی؟',ro:'Az Tehrānam. To chi?',en:'I\'m from Tehran. And you?'},
  {who:'A',name:'سارا Sara',fa:'منم از تهرانم! چه جالب!',ro:'Manam az Tehrānam! Che jāleb!',en:'I\'m from Tehran too! How interesting!'},
]},
culture:{icon:'🤝',tag:'Etiquette',title:'Ta\'arof — The Art of Persian Politeness',
fa:'بفرمایید!',ro:'Befarmayyid!',en:'"Please, go ahead / help yourself!"',
body:'Ta\'arof (تعارف) is a cornerstone of Iranian social life — a ritual politeness where people offer more than they intend and refuse more than they want. If you admire something in someone\'s home, they will likely offer it to you ("it\'s yours" — مال شماست). You must refuse politely at least twice before accepting. When entering a door, both people will insist the other goes first — "بفرمایید!" (after you!). Understanding ta\'arof helps you navigate Iranian hospitality gracefully.'},
quiz:[
  {q:'سلام means:',c:'سلام',opts:['Goodbye','Hello','Thank you','Please'],a:1},
  {q:'خوبم ممنون means:',c:'',opts:['Nice to meet you','Good morning','I\'m well, thank you','See you later'],a:2},
  {q:'اسمت چیه means:',c:'',opts:['How are you?','Where are you from?','What is your name?','How old are you?'],a:2},
  {q:'خداحافظ means:',c:'خداحافظ',opts:['Hello','Goodbye','Welcome','Sorry'],a:1},
  {q:'Ta\'arof is:',c:'',opts:['A Persian dish','A type of music','Ritual politeness','A greeting'],a:2},
]},

{id:'c2',type:'conv',num:'C2',title:'Numbers, Age & Time',fa:'اعداد، سن و زمان',
intro:'A1–A2 level. Persian numbers, telling time, asking ages. Persian uses its own numeral shapes (٠١٢٣...) but Western numerals (0123...) are common too.',
phrases:[
  {fa:'چند سالته؟',ro:'Chand sālate?',en:'How old are you? (informal)'},
  {fa:'بیست و سه سالمه.',ro:'Bist-o-se sālame.',en:'I am 23 years old.'},
  {fa:'ساعت چنده؟',ro:'Sā\'at chande?',en:'What time is it?'},
  {fa:'ساعت سه است.',ro:'Sā\'at se ast.',en:'It is 3 o\'clock.'},
  {fa:'الان چه روزیه؟',ro:'Alān che ruzi-ye?',en:'What day is it today?'},
  {fa:'امروز دوشنبه‌ست.',ro:'Emruz doshanbe-st.',en:'Today is Monday.'},
  {fa:'دیر شد!',ro:'Dir shod!',en:'We\'re late!'},
],
numbers:[
  {n:'یک',r:'yek',v:1},{n:'دو',r:'do',v:2},{n:'سه',r:'se',v:3},{n:'چهار',r:'chahār',v:4},
  {n:'پنج',r:'panj',v:5},{n:'شش',r:'shesh',v:6},{n:'هفت',r:'haft',v:7},{n:'هشت',r:'hasht',v:8},
  {n:'نه',r:'noh',v:9},{n:'ده',r:'dah',v:10},{n:'بیست',r:'bist',v:20},{n:'صد',r:'sad',v:100},
],
dialogue:{title:'Friends making plans',
lines:[
  {who:'A',name:'نیلوفر Nilufar',fa:'ساعت چنده؟ دیرم میشه!',ro:'Sā\'at chande? Diram mishe!',en:'What time is it? I\'m going to be late!'},
  {who:'B',name:'امیر Amir',fa:'ساعت هشت و نیمه. کجا میری؟',ro:'Sā\'at hasht-o-nime. Kojā miri?',en:'It\'s half past eight. Where are you going?'},
  {who:'A',name:'نیلوفر Nilufar',fa:'کلاس فارسی دارم ساعت نه.',ro:'Kelās-e Fārsi dāram sā\'at noh.',en:'I have a Persian class at nine.'},
  {who:'B',name:'امیر Amir',fa:'هنوز بیست دقیقه مونده. نگران نباش!',ro:'Hanuz bist daqiqe munde. Nagarān nabāsh!',en:'There\'s still twenty minutes left. Don\'t worry!'},
]},
culture:{icon:'📅',tag:'Calendar',title:'The Persian Solar Calendar — شمسی',
fa:'نوروز مبارک!',ro:'Nowruz Mobārak!',en:'"Happy New Year!"',
body:'Iran uses the Solar Hijri calendar (تقویم شمسی). The Persian New Year, Nowruz (نوروز — "New Day"), falls on the Spring Equinox, around March 20–21. The year 2025 CE = 1404 in the Persian calendar. Nowruz is celebrated for 13 days with the Haft-Seen table (هفت‌سین) — seven items starting with the letter "s" (sin): sprouted wheat, apples, garlic, sumac, vinegar, coins, and hyacinth. It is the biggest celebration in Iranian culture.'},
quiz:[
  {q:'ساعت چنده means:',c:'',opts:['What day is it?','What time is it?','How old are you?','Where are you?'],a:1},
  {q:'بیست means:',c:'بیست',opts:['10','15','20','25'],a:2},
  {q:'Nowruz falls on:',c:'',opts:['December 21','January 1','The Spring Equinox','The Autumn Equinox'],a:2},
  {q:'دیر شد means:',c:'دیر شد',opts:['It\'s early','We\'re late','Time to go','Let\'s wait'],a:1},
  {q:'The Persian year 1404 corresponds roughly to:',c:'',opts:['2003','2015','2025','2030'],a:2},
]},

{id:'c3',type:'conv',num:'C3',title:'Food, Cafés & Restaurants',fa:'غذا و رستوران',
intro:'A2 level. Order food, talk about likes and dislikes, navigate a Persian restaurant. Iranian cuisine is one of the world\'s great food traditions.',
phrases:[
  {fa:'یه چای لطفاً.',ro:'Ye chāy lotfan.',en:'One tea please.'},
  {fa:'منوی غذا دارید؟',ro:'Meno-ye ghazā dārid?',en:'Do you have a food menu?'},
  {fa:'غذای ایرانی دوست دارم.',ro:'Ghazā-ye Irāni dust dāram.',en:'I love Iranian food.'},
  {fa:'چی پیشنهاد می‌دید؟',ro:'Chi pishnahād midid?',en:'What do you recommend?'},
  {fa:'حساب لطفاً.',ro:'Hesāb lotfan.',en:'The bill please.'},
  {fa:'خیلی خوشمزه بود!',ro:'Kheyly khoshmaze bud!',en:'It was very delicious!'},
  {fa:'گیاهخوارم.',ro:'Giyāhkhāram.',en:'I am vegetarian.'},
],
food:[
  {fa:'چلو کباب',ro:'chelo kabāb',en:'Rice with grilled meat — Iran\'s national dish'},
  {fa:'خورش قرمه سبزی',ro:'khoresh-e ghorme sabzi',en:'Herb & bean stew — most beloved stew'},
  {fa:'آش رشته',ro:'āsh-e reshte',en:'Noodle soup — eaten at Nowruz'},
  {fa:'دوغ',ro:'dugh',en:'Yogurt drink — salty, refreshing'},
  {fa:'سمنو',ro:'samanu',en:'Sweet wheat pudding — Nowruz tradition'},
],
dialogue:{title:'At a traditional restaurant in Isfahan',
lines:[
  {who:'A',name:'گارسون Waiter',fa:'بفرمایید! چی میل دارید؟',ro:'Befarmayyid! Chi meyl dārid?',en:'Welcome! What would you like?'},
  {who:'B',name:'مهمان Guest',fa:'یه چلو کباب و یه دوغ لطفاً.',ro:'Ye chelo kabāb o ye dugh lotfan.',en:'One chelo kabab and one dough please.'},
  {who:'A',name:'گارسون Waiter',fa:'کباب کوبیده می‌خواید یا جوجه؟',ro:'Kabāb-e kubide mikhāyid yā juje?',en:'Do you want ground meat kabab or chicken?'},
  {who:'B',name:'مهمان Guest',fa:'کوبیده، ممنون. و آیا سوپ دارید؟',ro:'Kubide, mamnun. Va āyā sup dārid?',en:'Ground meat, thank you. And do you have soup?'},
  {who:'A',name:'گارسون Waiter',fa:'بله، آش رشته داریم.',ro:'Bale, āsh-e reshte dārim.',en:'Yes, we have noodle soup.'},
  {who:'B',name:'مهمان Guest',fa:'عالیه! حتماً امتحان می‌کنم.',ro:'\'Āliye! Hatman emtahān mikonam.',en:'Wonderful! I\'ll definitely try it.'},
]},
culture:{icon:'🍽️',tag:'Food',title:'Persian Cuisine — A Living Poetry',
fa:'نوش جان!',ro:'Nushe jān!',en:'"May it nourish your soul!" (Bon appétit)',
body:'Persian food is built on aromatic herbs, dried fruits, nuts, and saffron (زعفران za\'farān) — the world\'s most expensive spice, grown in Khorasan. Every Iranian household has its own recipe for ghorme sabzi (herb stew), considered the most loved dish. Bread (نان nān) comes in many forms: lavash (thin flatbread), sangak (baked on river stones), barbari (thick oblong loaf). Tea after meals is non-negotiable.'},
quiz:[
  {q:'نوش جان means:',c:'',opts:['Welcome','Goodbye','Bon appétit','Good night'],a:2},
  {q:'چلو کباب is:',c:'',opts:['A soup','Rice with grilled meat','A dessert','A drink'],a:1},
  {q:'حساب لطفاً means:',c:'',opts:['The menu please','One more please','The bill please','Thank you'],a:2},
  {q:'What is دوغ?',c:'دوغ',opts:['Sweet tea','Yogurt drink','Fruit juice','Sparkling water'],a:1},
  {q:'خیلی خوشمزه means:',c:'',opts:['Very expensive','Very spicy','Very delicious','Very small'],a:2},
]},

{id:'c4',type:'conv',num:'C4',title:'Shopping & Bargaining',fa:'خرید و چانه‌زنی',
intro:'A2 level. Persian markets (bazaars) are legendary. Learn to ask prices, bargain politely, and shop. The Grand Bazaar of Tehran is one of the largest covered markets on Earth.',
phrases:[
  {fa:'این چند تومنه؟',ro:'In chand tumāne?',en:'How much is this? (in Tomans)'},
  {fa:'گرونه! تخفیف میدید؟',ro:'Girone! Takhfif midid?',en:'It\'s expensive! Can you give a discount?'},
  {fa:'این رو می‌خوام.',ro:'Ino mikhām.',en:'I want this one.'},
  {fa:'یه کم ارزون‌تر نمیشه؟',ro:'Ye kam arzuntar nemishe?',en:'Can\'t it be a little cheaper?'},
  {fa:'باشه، می‌خرم.',ro:'Bāshe, mikharam.',en:'OK, I\'ll buy it.'},
  {fa:'کجا می‌تونم ... پیدا کنم؟',ro:'Kojā mitoonam ... peydā konam?',en:'Where can I find ...?'},
  {fa:'فقط نگاه می‌کنم.',ro:'Faqat negāh mikonam.',en:'I\'m just looking.'},
],
dialogue:{title:'In the bazaar, buying a carpet',
lines:[
  {who:'A',name:'مشتری Customer',fa:'سلام. این فرش چند تومنه؟',ro:'Salām. In farsh chand tumāne?',en:'Hello. How much is this carpet?'},
  {who:'B',name:'فروشنده Seller',fa:'سلام! این دست‌بافته. سه میلیونه.',ro:'Salām! In dast-bāfte. Se milyone.',en:'Hello! This is handwoven. It\'s three million (Tomans).'},
  {who:'A',name:'مشتری Customer',fa:'گرونه! دو میلیون چطوره؟',ro:'Girone! Do milyon chetore?',en:'That\'s expensive! How about two million?'},
  {who:'B',name:'فروشنده Seller',fa:'نمیشه آقا. دو و نیم، آخرین قیمته.',ro:'Nemishe āghā. Do-o-nim, ākharin ghimate.',en:'Can\'t do it, sir. Two and a half — final price.'},
  {who:'A',name:'مشتری Customer',fa:'باشه. قبوله. بسته‌بندی می‌کنید؟',ro:'Bāshe. Qabule. Baste-bandi mikonid?',en:'OK. Deal. Can you pack it?'},
]},
culture:{icon:'🏺',tag:'Bazaar',title:'The Persian Bazaar — بازار',
fa:'بازار',ro:'Bāzār',en:'"Market / Bazaar"',
body:'The word "bazaar" comes directly from Persian (بازار). Persian bazaars are ancient commercial hubs — the Grand Bazaar of Tehran (بازار بزرگ تهران) covers 10km² and employs over 100,000 people. Shopping here is a social ritual: tea is offered, conversation flows, and bargaining is expected. Never accept the first price. The bazaar traditionally sat at the heart of the city next to the mosque — commerce and faith intertwined. Persian carpets (فرش) are among the world\'s greatest art forms, with knot counts exceeding 1,000 per square inch.'},
quiz:[
  {q:'این چند تومنه means:',c:'',opts:['What is this?','How much is this?','I want this','Too expensive'],a:1},
  {q:'تخفیف means:',c:'تخفیف',opts:['Price','Discount','Expensive','Change'],a:1},
  {q:'فقط نگاه می‌کنم means:',c:'',opts:['I\'ll buy it','How much?','Just looking','Very nice'],a:2},
  {q:'"Bazaar" is a word from:',c:'',opts:['Arabic','Turkish','Persian','French'],a:2},
  {q:'باشه means:',c:'باشه',opts:['No','Maybe','OK / alright','Never'],a:2},
]},

{id:'c5',type:'conv',num:'C5',title:'Family & Friends',fa:'خانواده و دوستان',
intro:'A2–B1 level. Talk about your family, describe relationships, and discuss friends. Family is central to Iranian culture — often multigenerational homes.',
phrases:[
  {fa:'خانواده‌ام بزرگه.',ro:'Khānevāde-am bozorge.',en:'My family is large.'},
  {fa:'چند تا برادر خواهر داری؟',ro:'Chand tā barādar khāhar dāri?',en:'How many siblings do you have?'},
  {fa:'یه برادر و دو خواهر دارم.',ro:'Ye barādar o do khāhar dāram.',en:'I have one brother and two sisters.'},
  {fa:'ازدواج کردی؟',ro:'Ezdevāj kardi?',en:'Are you married?'},
  {fa:'نه، هنوز مجردم.',ro:'Na, hanuz mojradam.',en:'No, I\'m still single.'},
  {fa:'دوست صمیمی‌ام رضاست.',ro:'Dust-e samimi-am Rezāst.',en:'My close friend is Reza.'},
  {fa:'با هم بزرگ شدیم.',ro:'Bā ham bozorg shodim.',en:'We grew up together.'},
],
family:[
  {fa:'پدر',ro:'pedar',en:'father'},{fa:'مادر',ro:'mādar',en:'mother'},{fa:'برادر',ro:'barādar',en:'brother'},
  {fa:'خواهر',ro:'khāhar',en:'sister'},{fa:'پسر',ro:'pesar',en:'son/boy'},{fa:'دختر',ro:'dokhtar',en:'daughter/girl'},
  {fa:'پدربزرگ',ro:'pedar-bozorg',en:'grandfather'},{fa:'مادربزرگ',ro:'mādar-bozorg',en:'grandmother'},
],
dialogue:{title:'Catching up with an old friend',
lines:[
  {who:'A',name:'شیرین Shirin',fa:'شیرین! چقدر وقته ندیدمت!',ro:'Shirin! Cheghadr vaghte nadidamat!',en:'Shirin! It\'s been so long since I saw you!'},
  {who:'B',name:'پریسا Parisa',fa:'پریسا جون! حالت چطوره؟ خانواده‌ات خوبن؟',ro:'Parisā jun! Hālat chetore? Khānevāde-at khuban?',en:'Parisa dear! How are you? Is your family well?'},
  {who:'A',name:'شیرین Shirin',fa:'همه خوبن، ممنون. بابام بازنشسته شد.',ro:'Hame khuban, mamnun. Bābām bāz-nashaste shod.',en:'Everyone is well, thank you. My dad just retired.'},
  {who:'B',name:'پریسا Parisa',fa:'آره؟ ماشاالله! و تو؟ هنوز مجردی؟',ro:'Āre? Māshāllāh! Va to? Hanuz mojradi?',en:'Really? Mashallah! And you? Still single?'},
  {who:'A',name:'شیرین Shirin',fa:'نه، نامزد کردم! ماه دیگه عروسیمه.',ro:'Na, nāmzad kardam! Māh-e dige arusimeh.',en:'No, I got engaged! My wedding is next month!'},
  {who:'B',name:'پریسا Parisa',fa:'مبارک باشه! خوشبخت بشید!',ro:'Mobārak bāshe! Khoshbakht beshid!',en:'Congratulations! May you be happy!'},
]},
culture:{icon:'👨‍👩‍👧',tag:'Family',title:'Family Values in Iranian Culture',
fa:'خانواده',ro:'Khānevāde',en:'"Family"',
body:'Family (خانواده) is the foundation of Iranian society. Multigenerational living is common — grandparents, parents, and children often under one roof. The concept of family honour (آبروی خانوادگی ābruy-e khānevādegi) carries great weight. Friday (جمعه, jome) is family day — the day off in Iran — when extended family gathers for a large lunch. Addressing elders respectfully (using plural "you" — شما shomā instead of تو to) is essential etiquette.'},
quiz:[
  {q:'مادر means:',c:'مادر',opts:['Father','Sister','Mother','Grandmother'],a:2},
  {q:'مبارک باشه means:',c:'',opts:['Good night','Welcome','Congratulations','Thank you'],a:2},
  {q:'مجرد means:',c:'مجرد',opts:['Married','Divorced','Single','Engaged'],a:2},
  {q:'Friday is significant in Iran because:',c:'',opts:['It\'s a market day','It\'s the day off and family day','It\'s a national holiday','It\'s a religious fast'],a:1},
  {q:'Using شما instead of تو shows:',c:'',opts:['Anger','Intimacy','Respect/formality','Confusion'],a:2},
]},

{id:'c6',type:'conv',num:'C6',title:'Work & Daily Life',fa:'کار و زندگی روزمره',
intro:'B1 level. Talk about jobs, daily routines, and work life in Iran. Iran has a young, educated, and tech-savvy population.',
phrases:[
  {fa:'چیکاره‌ای؟',ro:'Chikāre-i?',en:'What do you do? (informal)'},
  {fa:'مهندسم.',ro:'Mohandesam.',en:'I\'m an engineer.'},
  {fa:'کجا کار می‌کنی؟',ro:'Kojā kār mikoni?',en:'Where do you work?'},
  {fa:'تو یه شرکت خصوصی کار می‌کنم.',ro:'Tu ye sherkat-e khosousi kār mikonam.',en:'I work in a private company.'},
  {fa:'حقوقت خوبه؟',ro:'Hoghughat khube?',en:'Is your salary good?'},
  {fa:'کار پیدا کردن سخته.',ro:'Kār peydā kardan sakhte.',en:'Finding work is hard.'},
  {fa:'دورکاری می‌کنم.',ro:'Durkāri mikonam.',en:'I work remotely.'},
],
jobs:[
  {fa:'دکتر',ro:'doktor',en:'doctor'},{fa:'معلم',ro:'mo\'allem',en:'teacher'},{fa:'مهندس',ro:'mohandes',en:'engineer'},
  {fa:'برنامه‌نویس',ro:'barnāme-nevis',en:'programmer'},{fa:'هنرمند',ro:'honarmand',en:'artist'},
  {fa:'کارمند',ro:'kārmand',en:'employee/clerk'},{fa:'دانشجو',ro:'dāneshjoo',en:'university student'},
],
dialogue:{title:'Meeting at a work conference in Tehran',
lines:[
  {who:'A',name:'کاوه Kāveh',fa:'سلام، کاوه‌ام. شما تو این شرکت کار می‌کنید؟',ro:'Salām, Kāveham. Shomā tu in sherkat kār mikonid?',en:'Hi, I\'m Kaveh. Do you work at this company?'},
  {who:'B',name:'نازنین Nāznin',fa:'نه، از یه استارتاپ دیگه اومدم. نازنینم.',ro:'Na, az ye startāp-e dige umadam. Nāzninam.',en:'No, I came from a different startup. I\'m Nazanin.'},
  {who:'A',name:'کاوه Kāveh',fa:'چه کاری می‌کنید؟',ro:'Che kāri mikonid?',en:'What kind of work do you do?'},
  {who:'B',name:'نازنین Nāznin',fa:'برنامه‌نویسم. روی هوش مصنوعی کار می‌کنم.',ro:'Barnāme-nevisam. Ruy-e hushe masnu\'i kār mikonam.',en:'I\'m a programmer. I work on artificial intelligence.'},
  {who:'A',name:'کاوه Kāveh',fa:'جالبه! منم تو حوزه فناوری کار می‌کنم.',ro:'Jālebe! Manam tu howze-ye fanāvari kār mikonam.',en:'Interesting! I also work in the tech field.'},
]},
culture:{icon:'💼',tag:'Economy',title:'Iran\'s Young, Tech-Driven Workforce',
fa:'ایران در حال تغییر است.',ro:'Irān dar hāl-e taghyir ast.',en:'"Iran is changing."',
body:'Iran has one of the Middle East\'s highest rates of university graduates, with over 50% of students being women. Tehran has a vibrant startup scene — Iranian engineers, programmers, and entrepreneurs are prominent across the global tech industry. Despite economic pressures, Iranian youth are highly educated, multilingual, and resourceful. The city of Tehran alone has a population of 15+ million people, making it one of the world\'s megacities.'},
quiz:[
  {q:'چیکاره‌ای means:',c:'',opts:['How are you?','What do you do?','Where are you?','When did you come?'],a:1},
  {q:'مهندس means:',c:'مهندس',opts:['Doctor','Teacher','Engineer','Manager'],a:2},
  {q:'دانشجو means:',c:'دانشجو',opts:['Professor','University student','School child','Graduate'],a:1},
  {q:'دورکاری means:',c:'دورکاری',opts:['Overtime','Remote work','Part-time','Commuting'],a:1},
  {q:'What percentage of Iranian university students are women?',c:'',opts:['About 20%','About 35%','Over 50%','About 45%'],a:2},
]},

// ==================== CULTURE/TRAVEL ====================
{id:'t1',type:'cult',num:'T1',title:'Persian History — Ancient Roots',fa:'تاریخ ایران',
intro:'Iran is one of the world\'s oldest continuous civilizations. From Cyrus the Great to the Safavid Empire, Persian history spans 3,000+ recorded years.',
timeline:[
  {year:'c. 550 BCE',title:'Achaemenid Empire — هخامنشیان',body:'Cyrus the Great (کوروش بزرگ) founded the first Persian Empire — the largest empire the world had seen. His Cyrus Cylinder is considered the world\'s first human rights declaration. The empire stretched from Greece to India.',fa:'کوروش بزرگ'},
  {year:'330 BCE',title:'Alexander\'s Conquest — اسکندر',body:'Alexander the Great conquered Persia and burned Persepolis (تخت جمشید). Yet Persian culture absorbed and transformed its conquerors — as it would do repeatedly throughout history.',fa:'تخت جمشید'},
  {year:'224–651 CE',title:'Sassanid Empire — ساسانیان',body:'The second great Persian empire. Zoroastrianism (زرتشت) was the state religion. Persian became a sophisticated literary language. The empire fell to the Arab Islamic conquest in 651 CE.',fa:'زرتشت'},
  {year:'9th–11th c.',title:'Islamic Golden Age — رنسانس ایرانی',body:'Persian scholars led the world in mathematics, astronomy, medicine, and philosophy. Ibn Sina (ابن سینا — Avicenna) wrote the Canon of Medicine, used in European universities for 600 years.',fa:'ابن سینا'},
  {year:'1501–1736',title:'Safavid Empire — صفویان',body:'Shah Ismail I established Shia Islam as the state religion. Isfahan (اصفهان) became one of the world\'s most beautiful cities. Persian art, architecture, and poetry reached their zenith.',fa:'اصفهان'},
  {year:'1979',title:'Islamic Revolution — انقلاب اسلامی',body:'The Shah was overthrown and the Islamic Republic was established under Ayatollah Khomeini. Iran remains the Islamic Republic today, though society is complex, diverse, and constantly evolving.',fa:'انقلاب'},
],
culture:{icon:'🏛️',tag:'Heritage',title:'Persepolis — تخت جمشید',
fa:'تخت جمشید، تخت شاهان جهان.',ro:'Takht-e Jamshid, takht-e shāhān-e jahān.',en:'"Persepolis, throne of the kings of the world."',
body:'Persepolis (تخت جمشید — "Throne of Jamshid") in Fars Province was the ceremonial capital of the Achaemenid Empire, built around 518 BCE. Its carved reliefs show delegations from 23 nations bringing tribute — a vision of a multicultural empire. Burned by Alexander in 330 BCE, its ruins survive and are a UNESCO World Heritage Site. Every Iranian knows Persepolis as a symbol of civilizational pride.'},
quiz:[
  {q:'Cyrus the Great founded:',c:'',opts:['The Sassanid Empire','The Achaemenid Empire','The Safavid Empire','The Parthian Empire'],a:1},
  {q:'تخت جمشید is:',c:'تخت جمشید',opts:['A city in Tehran','Persepolis — ancient ceremonial capital','A famous mosque','A mountain peak'],a:1},
  {q:'The Safavid Empire established which religion as state religion?',c:'',opts:['Sunni Islam','Zoroastrianism','Shia Islam','Christianity'],a:2},
  {q:'Ibn Sina (Avicenna) was famous for:',c:'',opts:['Poetry','Mathematics only','Medicine and philosophy','Architecture'],a:2},
  {q:'The Islamic Revolution in Iran was in:',c:'',opts:['1953','1963','1979','1989'],a:2},
]},

{id:'t2',type:'cult',num:'T2',title:'Famous Cities — Tehran & Isfahan',fa:'تهران و اصفهان',
intro:'Iran\'s two most iconic cities: Tehran, the vast modern capital, and Isfahan, the jewel of Safavid architecture. Each has its own soul.',
cities:[
  {name:'Tehran',fa:'تهران',desc:'Capital and megacity of 15+ million. The Alborz mountains frame its northern skyline with ski slopes. A city of traffic, culture, incredible food, and palpable energy.',sights:'Milad Tower · Golestan Palace · Grand Bazaar · Darband hiking trail · Tehran Museum of Contemporary Art'},
  {name:'Isfahan',fa:'اصفهان',desc:'"Isfahan is half the world" (اصفهان نصف جهان). The Safavid capital features the world\'s most beautiful central square — Naqsh-e Jahan, UNESCO-listed.',sights:'Naqsh-e Jahan Square · Sheikh Lotfallah Mosque · Khaju Bridge · Vank Cathedral · Si-o-Se Pol bridge'},
],
phrases:[
  {fa:'کجا هستیم؟',ro:'Kojā hastim?',en:'Where are we?'},
  {fa:'این بنا مال کِی‌ه؟',ro:'In banā māl-e kihe?',en:'What era is this building from?'},
  {fa:'بلیط چند تومنه؟',ro:'Belit chand tumāne?',en:'How much is the ticket?'},
  {fa:'راهنما می‌خوام.',ro:'Rāhnamā mikhām.',en:'I want a guide.'},
  {fa:'این مسجد واقعاً باشکوهه.',ro:'In masjed vāqe\'an bāshokohe.',en:'This mosque is truly magnificent.'},
],
culture:{icon:'🕌',tag:'Architecture',title:'Naqsh-e Jahan Square — نقش جهان',
fa:'اصفهان نصف جهان است.',ro:'Esfahān nesf-e jahān ast.',en:'"Isfahan is half the world."',
body:'Naqsh-e Jahan ("Image of the World") Square in Isfahan was built by Shah Abbas I around 1602. At 512m × 163m, it is one of the largest public squares on Earth, surrounded by the Imam Mosque, Sheikh Lotfallah Mosque, Ali Qapu Palace, and the Grand Bazaar. The tilework uses a mathematical mosaic system predating Western computer graphics. Polo was played here — the goalposts still stand. UNESCO declared it a World Heritage Site in 1979.'},
quiz:[
  {q:'اصفهان نصف جهان means:',c:'',opts:['Isfahan is the capital','Isfahan is half the world','Isfahan is ancient','Isfahan is beautiful'],a:1},
  {q:'Tehran is home to approximately:',c:'',opts:['3 million','8 million','15+ million','25 million'],a:2},
  {q:'Naqsh-e Jahan Square was built by:',c:'',opts:['Cyrus the Great','Shah Abbas I','Rumi','Hafez'],a:1},
  {q:'Si-o-Se Pol means:',c:'سی‌وسه‌پل',opts:['Bridge of Kings','Bridge of 33 Arches','The Great Bridge','Stone Bridge'],a:1},
  {q:'Which sport was historically played at Naqsh-e Jahan?',c:'',opts:['Wrestling','Archery','Polo','Football'],a:2},
]},

{id:'t3',type:'cult',num:'T3',title:'Famous Cities — Shiraz & Persepolis',fa:'شیراز و تخت جمشید',
intro:'Shiraz is the city of poets, wine, roses, and gardens. Nearby lies Persepolis — the greatest surviving monument of ancient Persia.',
cities:[
  {name:'Shiraz',fa:'شیراز',desc:'City of Hafez and Saadi — Iran\'s two greatest lyric poets. Famous for its roses, gardens, and historically for wine (شراز wine takes its name from Shiraz). Warm, laid-back, beautiful.',sights:'Tomb of Hafez · Tomb of Saadi · Nasir-ol-Molk (Pink) Mosque · Eram Garden · Vakil Bazaar'},
  {name:'Persepolis',fa:'تخت جمشید',desc:'50km northeast of Shiraz. The Achaemenid ceremonial capital. Giant carved columns, bas-reliefs of subject nations, the Gate of All Nations. Built 518 BCE, burned 330 BCE.',sights:'Gate of All Nations · Apadana Palace · Hall of 100 Columns · Treasury · Royal Tombs at Naqsh-e Rostam'},
],
phrases:[
  {fa:'مقبره حافظ کجاست؟',ro:'Maqbare-ye Hāfez kojāst?',en:'Where is the tomb of Hafez?'},
  {fa:'چقدر باشکوهه!',ro:'Cheghadr bāshokohe!',en:'How magnificent it is!'},
  {fa:'عکس بگیریم؟',ro:'Aks begirim?',en:'Shall we take a photo?'},
  {fa:'تاریخ ایران خیلی غنیه.',ro:'Tārikh-e Irān kheyly ghanihe.',en:'Iranian history is very rich.'},
],
culture:{icon:'📖',tag:'Poetry',title:'Hafez — The Tongue of the Unseen',
fa:'الا یا ایها الساقی ادر کأساً و ناولها.',ro:'Alā yā ayyohā as-sāqi adir ka\'san wa nāwilhā.',en:'"Come, O Cupbearer, pass the cup around..."',
body:'Hafez (حافظ, 1315–1390) of Shiraz is considered Iran\'s greatest lyric poet. His Divan (دیوان) of ghazals (love poems) is found in virtually every Iranian home — used for فال حافظ (fāl-e Hāfez): opening randomly for spiritual guidance, like a sacred oracle. His tomb (آرامگاه حافظ) in Shiraz\'s Hafezieh garden is one of Iran\'s most visited sites. Millions come to read a ghazal and find meaning in its lines.'},
quiz:[
  {q:'Hafez was from:',c:'',opts:['Tehran','Isfahan','Shiraz','Tabriz'],a:2},
  {q:'فال حافظ is:',c:'',opts:['A food dish','Opening the Divan for guidance','A music tradition','A dance'],a:1},
  {q:'Persepolis was built approximately:',c:'',opts:['100 BCE','518 BCE','200 CE','1000 CE'],a:1},
  {q:'چقدر باشکوهه means:',c:'',opts:['How old is it?','How far is it?','How magnificent!','How expensive!'],a:2},
  {q:'The "Pink Mosque" is in:',c:'',opts:['Tehran','Isfahan','Shiraz','Tabriz'],a:2},
]},

{id:'t4',type:'cult',num:'T4',title:'Weather & Seasons in Iran',fa:'آب و هوای ایران',
intro:'Iran is a vast country with dramatically different climates — from ski slopes north of Tehran in winter to beach resorts on the Persian Gulf.',
seasons:[
  {icon:'🌸',s:'Spring — بهار',r:'bahār',temp:'10–25°C',desc:'Best travel season. Nowruz (New Year) in March. Gardens bloom, waterfalls flow, the whole country travels.'},
  {icon:'☀️',s:'Summer — تابستان',r:'tābestan',temp:'25–45°C',desc:'Very hot in most cities. Iranians escape to the Caspian coast or mountain villages. The north stays pleasant.'},
  {icon:'🍂',s:'Autumn — پاییز',r:'pāyiz',temp:'8–22°C',desc:'Beautiful, mild. Pomegranates ripen. Second-best travel season — fewer crowds than spring.'},
  {icon:'❄️',s:'Winter — زمستان',r:'zemestān',temp:'-5 to 15°C',desc:'Ski season! Dizin and Shemshak (near Tehran) have world-class slopes. Deserts stay mild and perfect for visiting.'},
],
weather_phrases:[
  {fa:'هوا چطوره؟',ro:'Havā chetore?',en:'How\'s the weather?'},
  {fa:'باران می‌آد.',ro:'Bārān miyād.',en:'It\'s raining.'},
  {fa:'هوا ابریه.',ro:'Havā abrihe.',en:'It\'s cloudy.'},
  {fa:'گرمای طاقت‌فرساست.',ro:'Garmā-ye tāqat-forsāst.',en:'It\'s unbearably hot.'},
  {fa:'برف می‌آد.',ro:'Barf miyād.',en:'It\'s snowing.'},
  {fa:'هوا عالیه!',ro:'Havā ālihe!',en:'The weather is perfect!'},
],
culture:{icon:'🌷',tag:'Season',title:'Nowruz — نوروز — The Persian New Year',
fa:'بهار که آمد، دل شادمان شد.',ro:'Bahār ke āmad, del shādmān shod.',en:'"When spring came, the heart became joyful."',
body:'Nowruz (نوروز — "New Day") is the Persian New Year, celebrated on the Spring Equinox (March 20–21). It is 3,000 years old, predating Islam. The Haft-Seen table (هفت‌سین) must have seven items starting with "س" (sin): سبزه (sabze, sprouts), سیب (sib, apple), سمنو (samanu, pudding), سرکه (serkeh, vinegar), سنجد (senjed, dried fruit), سکه (sekke, coins), سیر (sir, garlic). The 13th day, Sizdah-be-dar (سیزده به در), everyone must go outdoors — staying home is bad luck.'},
quiz:[
  {q:'بهار means:',c:'بهار',opts:['Summer','Spring','Autumn','Winter'],a:1},
  {q:'Nowruz falls on:',c:'',opts:['January 1','The Winter Solstice','The Spring Equinox','March 1'],a:2},
  {q:'برف می‌آد means:',c:'',opts:['It\'s raining','It\'s sunny','It\'s snowing','It\'s windy'],a:2},
  {q:'The Haft-Seen table has items starting with the letter:',c:'',opts:['الف (A)','ب (B)','س (S)','م (M)'],a:2},
  {q:'زمستان means:',c:'زمستان',opts:['Spring','Summer','Autumn','Winter'],a:3},
]},

{id:'t5',type:'cult',num:'T5',title:'Travel Tips & Practical Persian',fa:'راهنمای سفر',
intro:'B1 level practical Persian for travelers. Get around, stay safe, and connect with locals. Iranians are famously warm to foreign visitors.',
tips:[
  {icon:'🛂',title:'Visa & Entry',body:'Most nationalities require a visa. Tourist visas are typically issued on arrival at major airports. Always check current requirements before traveling.'},
  {icon:'💰',title:'Money',body:'Iran uses the Iranian Rial (ریال) officially, but people quote prices in Tomans (تومان) — one Toman = 10 Rials. International cards don\'t work — bring cash (Euros or USD are best).'},
  {icon:'👗',title:'Dress Code',body:'Women must wear hijab (حجاب) in public — a headscarf plus loose clothing. Men should avoid shorts in formal/religious settings. Pack light, loose, natural fabrics.'},
  {icon:'📱',title:'Communications',body:'VPN is widely used. SIM cards are cheap and available. WiFi is common in hotels and cafés.'},
  {icon:'🚕',title:'Getting Around',body:'Tehran has a modern metro (مترو). Snapp (Iranian Uber) works in major cities. Intercity buses are comfortable. Trains are scenic and affordable.'},
  {icon:'🏥',title:'Safety',body:'Iran is generally very safe for tourists. Pickpocketing is rare. Locals often go out of their way to help foreign visitors — expect invitations to tea and meals!'},
],
phrases:[
  {fa:'کمکم کنید لطفاً.',ro:'Komakam konid lotfan.',en:'Please help me.'},
  {fa:'گم شدم.',ro:'Gom shodam.',en:'I\'m lost.'},
  {fa:'بیمارستان کجاست؟',ro:'Bimārestān kojāst?',en:'Where is the hospital?'},
  {fa:'متشکرم.',ro:'Motashakkeram.',en:'Thank you (formal).'},
  {fa:'ببخشید، فارسی بلد نیستم.',ro:'Bebakhshid, Fārsi balad nistam.',en:'Sorry, I don\'t know Persian.'},
  {fa:'کمی فارسی بلدم.',ro:'Kami Fārsi balad-am.',en:'I know a little Persian.'},
  {fa:'این رو به انگلیسی چی میگن؟',ro:'Ino be Engelisi chi migan?',en:'What is this called in English?'},
],
culture:{icon:'✈️',tag:'Traveler Tips',title:'Iranians & Foreign Visitors',
fa:'خوش آمدید!',ro:'Khosh āmadid!',en:'"Welcome!"',
body:'Iran consistently surprises first-time visitors with the warmth of its people. Strangers will invite you for tea, offer directions, insist on paying for your meal. The phrase خوش آمدید (Welcome!) is genuine and heartfelt. Learning even a few Persian words creates instant goodwill and delight. Iranians are deeply proud of their culture and will love sharing it with you. The most important phrase you can know: ایران خیلی زیباست — "Iran is very beautiful!"'},
quiz:[
  {q:'گم شدم means:',c:'گم شدم',opts:['I\'m tired','I\'m hungry','I\'m lost','I\'m late'],a:2},
  {q:'In Iran, prices are typically quoted in:',c:'',opts:['Rials','Dollars','Tomans','Euros'],a:2},
  {q:'Women travelers in Iran must wear:',c:'',opts:['Full niqab','Hijab (headscarf + loose clothing)','Nothing specific','A chador only'],a:1},
  {q:'خوش آمدید means:',c:'',opts:['Goodbye','Thank you','Welcome','Good morning'],a:2},
  {q:'متشکرم is:',c:'متشکرم',opts:['Informal thank you','Formal thank you','Please','Sorry'],a:1},
]},

];
